- bangpy-ops/ops/nonzero/nonzero.py
- bangpy-ops/ops/nonzero/nonzero_count.py
原有 NonZero算子，遇到shape较大的输入时，每次计算self.nram_size大小，如果迭代一次计算的输出为零，memcpy会出现错误。本次提交修复这个问题。
> feat(nonzro):Fix nonzero small output cases are not supported

- .github/workflows/ci.yaml
1. set nightly test at 15:00 according to time of CI's execution on Github.
> fix(bangc-ops): set nightly test at 15:00 according to time of CI's execution on GitHub

- bangc-ops/kernels/roi_crop/roi_crop.cpp
- bangc-ops/kernels/roi_crop/roi_crop_block.mlu
- bangc-ops/mlu_op.h
- bangc-ops/mlu_op_kernel.h
- bangc-ops/test/mlu_op_gtest/mlu_op_test_proto/mlu_op_test.proto
- bangc-ops/test/mlu_op_gtest/src/zoo/roi_crop_forward/roi_crop_forward.cpp
- bangc-ops/test/mlu_op_gtest/src/zoo/roi_crop_forward/roi_crop_forward.h
- bangc-ops/test/mlu_op_gtest/src/zoo/roi_crop_forward/test_case/case_0.prototxt
新增roi_crop_forward算子，提供获取感兴趣区域特征值的功能
- **影响范围/算子**：roi_crop_forward
- **影响版本/分支**：master
算子采用静态阈值标准：diffs=[diff1，diff2]，diff1<=3e-3 && diff2 <= 3e-3。
|      序号      |           需求           |      需求详情       |
|----|----|----|
|1|支持硬件 |MLU290、MLU370|
|2|job类型|U1|
|3|DimXYZ|支持DimXYZ|
|4|可变|不支持各个维度可变|
|5|layout|input:支持NHWC<br>grid:支持ARRAY|
|6|多维|不支持多维|
|7|0元素|不支持0元素|
|8|转数提前|否|
|9|片外数据类型|float|
|10|片上数据类型|float|
|11|融合|否|
|12|规模限制|否|
|13|c不感知对齐|否|
|14|原位测试对齐|不支持|
|测试点|验收标准|测试结果(精度)|
|----|----|----|
|数据类型测试|FLOAT|[ OK ] roi_crop_forward/TestSuite.mluOp/1227 (3 ms)[----------] 1228 tests from roi_crop_forward/TestSuite (148200 ms total)[----------] Global test environment tear-down[ SUMMARY ] Total 1228 cases of 1 op(s).ALL PASSED[==========] 1228 test cases from 1 test suite ran. (148265 …
> [Feature](bangc_ops): Add new op roi_crop_forward

- bangc-ops/kernels/fill_zero/fill_zero.mlu
- bangc-ops/kernels/roi_crop/roi_crop.cpp
- bangc-ops/kernels/roi_crop/roi_crop_block.mlu
- bangc-ops/mlu_op.h
- bangc-ops/mlu_op_kernel.h
- bangc-ops/test/mlu_op_gtest/mlu_op_test_proto/mlu_op_test.proto
- bangc-ops/test/mlu_op_gtest/src/zoo/roi_crop_backward/roi_crop_backward.cpp
- bangc-ops/test/mlu_op_gtest/src/zoo/roi_crop_backward/roi_crop_backward.h
- bangc-ops/test/mlu_op_gtest/src/zoo/roi_crop_backward/test_case/case_0.prototxt
新增roi_crop_backward算子，是roi_crop_forward算子的反向
- **影响范围/算子**：roi_crop_backward
- **影响版本/分支**：master
算子采用静态阈值标准：diffs=[diff1，diff2]，diff1<=3e-3 && diff2 <= 3e-3。
|      序号      |           需求           |      需求详情       |
|----|----|----|
|1|支持硬件 |MLU290、MLU370|
|2|job类型|U1|
|3|DimXYZ|支持DimXYZ|
|4|可变|不支持各个维度可变|
|5|layout|gradInput和gradOutput:支持NHWC<br>grid:支持ARRAY|
|6|多维|不支持多维|
|7|0元素|不支持0元素|
|8|转数提前|否|
|9|片外数据类型|float|
|10|片上数据类型|float|
|11|融合|否|
|12|规模限制|否|
|13|c不感知对齐|否|
|14|原位测试对齐|不支持|
|测试点|验收标准|测试结果(精度)|
|----|----|----|
|数据类型测试|FLOAT|[----------] Global test environment tear-down[ SUMMARY  ] Total 1381 cases of 1 op(s).ALL PASSED.[==========] 1381 test cases from 1 test suite ran. (153401 ms total)[  PASSED  ] 1381 test cases.|
|多维张量测试|支持4维|[----------] Global test environment …
> [Feature](bangc-ops):Add new op roi_crop_backward

- bangc-ops/kernels/psroipool_forward/psroipool_forward.cpp
- bangc-ops/kernels/psroipool_forward/psroipool_forward_block.mlu
- bangc-ops/mlu_op.h
- bangc-ops/mlu_op_kernel.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/psroipool_forward/psroipool_forward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/psroipool_forward/psroipool_forward.h
- docs/bangc-docs/design_docs/psroipool_forward/psroipool_forward.md
<h3>1、修改描述</h3><p>添加算子描述</p><ul><li>影响范围/算子：psroipool_forward</li><li>影响版本/分支：master</li></ul><h5>1.1 精度验收标准</h5><p>算子采用静态阈值标准：diffs=[diff1，diff2]，diff1&lt;=3e-3 &amp;&amp; diff2 &lt;= 3e-3</p><p>由于框架问题mapping_channel暂不支持diff3，也采用diff1、diff2标准</p><p>1.2 算子方案CHECKLIST</p>
序号 | 需求 | 需求详情
-- | -- | --
1 | 支持硬件 | MLU290 MLU370
2 | job类型 | U1
3 | DimXYZ | 支持DimXYZ
4 | 可变 | 否
5 | layout | 支持NHWC类型layout
6 | 多维 | 不支持
7 | 0元素 | 支持
8 | 转数提前 | 不支持
9 | 片上数据类型 | float
10 | 片外数据类型 | float
11 | 融合 | 否
12 | 规模限制 | 无
13 | c不感知对齐 | 片外c方向不需要对齐
14 | 代码覆盖率 | 代码覆盖率原则上不低于95%
15 | 内存泄露 | MLU-OPS暂时不提供该功能
16 | IO计算效率检查 | 确保IO及计算效率正确
<h5>1.3新特性测试</h5>
测试点 | 验收标准 | 测试结果（精度）
-- | -- | --
数据类型测试 | FLOAT | [Error]:[mluOpPsRoiPoolForward] Check failed: input_dtype == MLUOP_DTYPE_FLOAT.
多维张量测试 | 支持4-2-4-4维 | …
> [Feature]: fix psroipool_forward comment

- bangc-ops/kernels/psroipool/psroipool.cpp
- docs/bangc-docs/design_docs/psroipool_backward/psroipool_backward.md
新增psroipool_backward算子，是psroipool_forward算子的反向
- **影响范围/算子**：psroipool_backward
- **影响版本/分支**：master
算子采用静态阈值标准：diffs=[diff1，diff2]，diff1<=3e-3 && diff2 <= 3e-3。
|      序号      |           需求           |      需求详情       |
|----|----|----|
|1|支持硬件 |MLU270、MLU290、MLU370|
|2|job类型|U1|
|3|DimXYZ|支持DimXYZ|
|4|可变|不支持各个维度可变|
|5|layout|top_grad、mapping_channel和bottom_grad:支持NHWC<br>rois:支持ARRAY|
|6|多维|不支持多维|
|7|0元素|不支持0元素|
|8|转数提前|否|
|9|片外数据类型|float|
|10|片上数据类型|float|
|11|融合|否|
|12|规模限制|否|
|13|c不感知对齐|否|
|14|原位测试对齐|不支持|
|测试点|验收标准|测试结果(精度)|
|----|----|----|
|数据类型测试|FLOAT|[----------] Global test environment tear-down [ SUMMARY  ] Total 169 cases of 1 op(s). ALL PASSED.[==========] 169 test cases from 1 test suite ran. (6002 ms total) [  PASSED  ] 169 test cases.|
|多维张量测试|支持4维|[----------] Global …
> [Fix](psroipool_backward):fix host code

- bangc-ops/kernels/prior_box/prior_box.cpp
添加算子描述
- 影响范围/算子：prior_box
- 影响版本/分支：master
- bug描述：output/var tensor最后一维度为4没有防呆
根据算子需求给出算子分类，及其对应的精度验收标准
该算子有两个输出
第一个输出output：
- 算子精度验收标准：diff1、diff2；
- 算子精度阈值描述：diff1 <= 3e-3 && diff2 <=3e-3；
第二个输出var：
- 算子精度验收标准：diff3；
- 算子精度阈值描述：diff3 == 0；
| 序号 | 需求           | 需求详情                                                     |
| ---- | -------------- | ------------------------------------------------------------ |
| 1    | 支持硬件       | MLU270/MLU290/MLU370                                         |
| 2    | job类型        | block                                                        |
| 3    | DimXYZ         | 支持DimXYZ                                                   |
| 4    | 可变           | 支持                                                         |
| 5    | layout         | ARRAY …
> [Fix](bangc-ops): Fix output/var shape[3] defensive bug.

- installer/centos7.5/SPECS/mluops-independent.spec
fix rpm build spec file for centos.
installer/centos7.5/SPEC/mluops-independent.spec
> [Fix](bangc-ops): fix rpm build spec file for centos.

- independent_build.sh
add test_tar package config when do packaging.
r0.1 independent_build.sh
> [Fix](bangc-ops): add test tar package configuration when do packaging.

- .gitignore
- bangc-ops/CMakeLists.txt
- bangc-ops/build.sh
- build.property
- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
- installer/independent/debian/install
- installer/ubuntu16.04/debian/install
fix packaging configure files
modified:   .gitignore
modified:   bangc-ops/CMakeLists.txt
modified:   bangc-ops/build.sh
modified:   installer/independent/debian/install
modified:   installer/ubuntu16.04/debian/install
> [Fix](bangc-ops): fix packaging configure files.

- bangc-ops/CMakeLists.txt
- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
fix centos install packgage configuration.
add project name into bangc-ops CMakeList
modified:   bangc-ops/CMakeLists.txt
> [Fix](bangc-ops): fix centos install packgage configuration.

- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
fix centos build dir name for package build.
> [Fix](bangc-ops): fix centos build dir name for package build.

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.cpp
- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.mlu
- docs/bangc-docs/design_docs/generate_proposals_v2/generate_proposals_v2.md
影响范围/算子：generate_proposals_v2
影响版本/分支：master
1.1 精度验收标准
按照[精度验收标准](https://github.com/Cambricon/mlu-ops/blob/1dd886d78b53f9e3b4783b948b7ba28b422f4851/docs/bangc-docs/design_docs/MLU_OPS%E7%B2%BE%E5%BA%A6%E9%AA%8C%E6%94%B6%E6%A0%87%E5%87%86.md)的要求明确本算子的精度标准
 generate_proposals_v2 是复合类算子。
rpn_rois参数精度设为 diff1 <= 3e-3 && diff2 <=3e-3。
rpn_roi_probs、rpn_rois_num、rpn_rois_batch_size的精度设置为 diff3=0。
1.2 算子方案CHECKLIST
序号 | 需求 | 需求详情
-- | -- | --
1 | 支持硬件 | MLU270MLU290MLU370
2 | job类型 | blockU1U4Ux
3 | DimXYZ | 支持DimXYZ
4 | 可变 | 不支持各个维度可变
5 | layout | ARRAY
6 | 多维 | 不支持多维
7 | 0元素 | 支持0元素
8 | 转数提前 | 否
9 | 片上数据类型 | float
10 | 片外数据类型 | float
11 | 融合 | 否
12 | 规模限制 |  
13 | c不感知对齐 | 否
14 | 代码覆盖率 |  
15 | 内存泄露 | 无
16 | IO计算效率检查 | 是
<h5 class="code-line" id="generate_proposals_v2算子测试报告-1.3算子限制" …
> [Fix](bangc-ops):fix the scores has same value.

- bangc-ops/core/tensor.h
- bangc-ops/core/type.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/include/pb_test_tools.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/executor.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/parser.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/pb_test_tools.cpp
To enable the mlu-ops to support complex data type case tests
Modified the gtest code to support complex data type test case
Note: Google Test filter = copy*
[==========] Running 16 test cases from 1 test suite.
[----------] Global test environment set-up.
[----------] 16 tests from copy/TestSuite
[ RUN      ] copy/TestSuite.mluOp/0
[MLU Hardware Time     ]: 2 (us)
[MLU Interface Time    ]: 64.959 (us)
[MLU IO Efficiency     ]: 0.000260417
[MLU Compute Efficiency]: 4.88281e-06
[MLU Workspace Size    ]: -1 (Bytes)
[MLU TheoryOps         ]: 10 (Ops)
[MLU TheoryIOs         ]: 160 (Bytes)
[MLU ComputeForce      ]: …
> [Feature](bangc-ops): modify gtest to support complex data type

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/ball_query/test_case/case_0.prototxt
之前合入的case_0.prototxt，input1:[16, 10176, 3], input2：[16, 10176, 3], output：[16, 10176, 10176]；输入输出的shape太大，运行时间长，导致跑流水时间过程。
修改后的shape：input1:[16, 126, 3], input2：[16, 256, 3], output：[16, 128, 128]
> [Docs](bangc-ops):For ball_query, reduce the input and output shape

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/ball_query/ball_query.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/ball_query/ball_query_general.cpp
> [TEST](ball_query): add api check cases for ball_query

- bangc-ops/kernels/ball_query/ball_query.mlu
- bangc-ops/mlu_op.h
之前对零元素处理不合理。首先 
PARAM_CHECK("[mluOpBallQuery]", new_xyz != NULL);
-  PARAM_CHECK("[mluOpBallQuery]", xyz != NULL);
-  PARAM_CHECK("[mluOpBallQuery]", idx != NULL);
上面代码表面new_xyz、xyz、idx都不支持零元素；与实际情况不符。
修改后：
new_xyz中元素个数为0 则返回MLUOP_STATUS_NOT_SUPPORTED
xyz[0] != 0且xyz[1] == 0 则放回success 否则返回MLUOP_STATUS_NOT_SUPPORTED
idx的元素个数为零，则放回success。（前面的new_xyz和xyz零元素的检查，到了这一行，idx[0] = B，和idx[1]=M都不为零，所以当idx的元素为零，只能是nsamle为0）
> [Fix](bangc-ops):Perfect zero-element inspection for ball_query

- bangc-ops/CMakeLists.txt
- bangc-ops/test/mlu_op_gtest/CMakeLists.txt
[Fix](bangc-ops): Fix cmakelists for kylin10 aarch64 build.
> [Fix](bangc-ops): Fix cmakelists for kylin10 aarch64 build.

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/prior_box/prior_box_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/three_interprolate_forward/three_interprolate_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/three_interprolate_forward/three_interprolate_forward_general.cpp
Adfd api check cases to ensure the correctness of parameters.
地址为空检查
```c++
mluOpStatus_t MLUOP_WIN_API mluOpThreeInterpolateForward(
mluOpHandle_t handle, const mluOpTensorDescriptor_t features_desc,
const void *features, const mluOpTensorDescriptor_t indices_desc, const void *indices,
const mluOpTensorDescriptor_t weights_desc, const void *weights,
const mluOpTensorDescriptor_t output_desc, void *output);
```
非0元素场景下：  
- handle = NULL
- features_desc = NULL
- feature = NULL
- indices_desc = NULL
- indices = NULL
- weight_desc = NULL
- weight = NULL
- output_desc = NULL
- output = NULL
参数异常检查
输入输出layout均为ARRAY
|shape{feature,indices,weight,output}|dtype{feature,indices,weight,output}|note|
|---|---|---| …
> test(three_interprolate_forward): add api check cases

- bangc-ops/CMakeLists.txt
- bangc-ops/test/mlu_op_gtest/CMakeLists.txt
Revert "[Fix](bangc-ops): Fix cmakelists for kylin10 aarch64 build.
> [Fix](bangc-ops): Fix cmakelists for ci. 

- bangc-ops/kernels/psroipool/psroipool_block.mlu
- bangc-ops/kernels/utils/common.h
If the kernel contains the std::min() and std::max() functions, the cncc compiler will not compile if it calls a higher version of gcc.
1) bangc-ops/kernels/psroipool/psroipool_block.cpp
2) bangc-ops/kernels/utils/common.h …
> [Fix](bangc-ops):fix max/min func

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.cpp
- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.mlu
- bangc-ops/mlu_op_kernel.h
<!DOCTYPE html><h3 cid="n207" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.5em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.43; cursor: text; white-space: pre-wrap; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; …
>  profiling generate proposals v2

- env.sh
> [Fix](bangc-ops): fix nueware_home environment variable name.

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxel_pooling_forward/voxel_pooling_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxel_pooling_forward/voxel_pooling_forward_general.cpp
> [TEST](voxel_pooling_forward):add api check cases for voxel_poolking_forward

- bangc-ops/kernels/roi_align_rotated/roi_align_rotated_block.mlu
fix code to support nan/inf data for rois
1) mlu-ops/bangc-ops/kernels/roi_align_rotated/roi_align_rotated_block.mlu
|        3       |         Layouts            |  NHWC …
> [Feature](bangc-ops):add op support nan/inf

- bangc-ops/test/mlu_op_gtest/CMakeLists.txt
使用cmake3.23在ubuntu20.04下 编译mlu-ops/bangc-ops 概率性出错，分析后发现是 api_gtest 和 pb_gtest 各自 include 了test_env.h，但是由于我们用了include_directories，api_gtest模块的编译可能实际命中的是pb_gtest下的test_env.h，从而出现问题（如果要稳定复现，可以CMakeLists.txt里面把和api_gtest不相干的target注释掉）
Using cmake3.23 to compile mlu-ops/bangc-ops under ubuntu20.04 has a probabilistic error. After analysis, it is found that api_gtest and pb_gtest each include `test_env.h`, but because we use `include_directories`, the `api_gtest` module compilation may actually hit the `test_env.h` under `pb_gtest`, resulting in problems (if you want to reproduce it stably, you can comment out the target irrelevant to `api_gtest` in CMakeLists.txt)
use target_include_directories instead of include_directories, also hack on bangc
> [Fix](bangc-ops): refine include directories searching under mlu_op_gtest

- bangc-ops/CMakeLists.txt
- bangc-ops/kernels/kernel_wrapper/export_statement.h
- bangc-ops/kernels/kernel_wrapper/wrapper.h
- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
- installer/independent/debian/install
Use .a in binary-ops to success mluti-system compiling.
libexternal_lib.so -> libextlib.a
NO TEST REPORT
NONE
NONE
NONE
NONE
Use .a in binary-ops to success mluti-system compiling.
> [Feature](bangc-ops): use .a file to replace .so file

- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
Fix package install error
installer/centos7.5/SPECS/mluops-independent.spec
installer/centos7.5/SPECS/mluops.spec
> [Fix](bangc-ops): remove libexternal.so related package info.

- installer/independent/debian/control
Sync installer info after delete ubuntu16.04 installer
installer/independent/debian/control
> [Fix](bangc-ops): sync debian installer info.

- bangc-ops/mlu_op.h
Modify mluop.h to remove alignment spaces.
- bangc-ops/mlu_op.h
Does not involve.
Please give a brief overview here, if you want to note and summarize the content.
> [Feature](bangc_ops):Modify mluop.h to remove alignment spaces.

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roi_crop_forward/roi_crop_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roiaware_pool3d_forward/roiaware_pool3d_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roiaware_pool3d_forward/roiaware_pool3d_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roiaware_pool3d_forward/roiaware_pool3d_forward_workspace.cpp
To check roiaware_pool3d_forward api params
Add api cases
```
[       OK ] negative_pts_idx_of_voxels_shape/roiaware_pool3d_forward_general.negative/2 (0 ms)
[ RUN      ] negative_pts_idx_of_voxels_shape/roiaware_pool3d_forward_general.negative/3
[2023-2-1 20:44:53] [MLUOP] [Error]: [mluOpRoiawarePool3dForward] Check failed: pts_idx_of_voxels_desc->dims[3] == out_z. 
[       OK ] negative_pts_idx_of_voxels_shape/roiaware_pool3d_forward_general.negative/3 (0 ms)
[ RUN      ] negative_pts_idx_of_voxels_shape/roiaware_pool3d_forward_general.negative/4
[2023-2-1 20:44:53] [MLUOP] [Error]: [mluOpRoiawarePool3dForward] Check failed: pts_idx_of_voxels_desc->dims[4] == max_pts_each_voxel. 
[       OK ] …
```
> [TEST](roiaware_pool3d_forward): add api check cases

- bangc-ops/CMakeLists.txt
Fix a core dump problem when running binary-ops.
bangc-ops/CMakeList.txt
None
> [Feature](bangc-ops): fix binary-ops core dump problem

- bangc-ops/kernels/voxel_pooling_forward/voxel_pooling_forward.cpp
add bangc ops voxel_pooling_forward gen_case op param.
bangc-ops/kernels/voxel_pooling_forward/voxel_pooling_forward.cpp
[^      OK ] ../../test/mlu_op_gtest/pb_gtest/src/zoo/voxel_pooling_forward/test_case/voxel_pooling_forward_20230203_18_27_47_279682_tid1149_device5.prototxt
[       OK ] voxel_pooling_forward/TestSuite.mluOp/0 (4679 ms)
[----------] 1 test from voxel_pooling_forward/TestSuite (4679 ms total)
[2023-2-3 18:32:56] [MLUOP] [Vlog]: TearDown CNRT environment.
[ SUMMARY  ] Total 1 cases of 1 op(s).
ALL PASSED.
[==========] 1 test case from 1 test suite ran. …
> [Feature](bangc_ops): voxel_pooling_forward add gen_case op param.

- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/mlu_op.h
Update binary ops version to 1.15.2.
bangc-ops/kernels/kernel_wrapper/lib/libextops.a
None
> [Feature](bangc-ops): update binary-ops version to 1.15.2.

- bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d.cpp
- bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d_union1.mlu
- bangc-ops/mlu_op.h
roiaware_pool3d delete support MLU200.
1) mlu-ops/bangc-ops/kernels/roiaware_pool3d/*
2) mlu-ops/bangc-ops/mlu_op.h
For dynamic threshold standard details.
|        1       |          Supported hardware         | MLU270 <br> MLU290 <br>MLU370<br>MLU590 |
|        2       |          Job types          |     U1     |
|        3       |         Layouts            | ARRAY   |
|        4       |         Whether multi-dimensions are supported              |    X     |
|        5 …
> [Feature](bangc_ops): roiaware_pool3d delete support MLU200.

- bangc-ops/CMakeLists.txt
- bangc-ops/README.md
- bangc-ops/build.sh
- bangc-ops/gen_mluops.py
- bangc-ops/test/mlu_op_gtest/CMakeLists.txt
fix libmluops.so file symbol visibility issue.
bangc-ops/CMakeLists.txt
bangc-ops/build.sh
bangc-ops/gen_mluops.py
bangc-ops/README.md
bangc-ops/test/mlu_op_gtest/CMakeLists.txt
修改描述：修改mlu-ops仓bangc-ops编译脚本，增加--version-script=ld.map 链接选项，从而隐藏libmluops.so动态库非对外暴露的符号，避免与cnnl等其他库发生符号冲突的问题
影响范围/算子：all
影响版本/分支：master
对比加--version-script 链接选项前后，生成动态库libmluops的global符号差异：
查看动态库global符号：nm -CD libmluops.so | grep " T "
libmluops.map 配置文件，在编译时通过gen_mluops.py自动生成
- 不添加--version-script 链接选项，发现很多非mlu_ops.h中定义的接口均暴露了，造成潜在的符号冲突问题
- 添加--version-script 链接选项，仅libmluops.map中定义的global符号暴露，其余均为local
- 结论：加 -Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/libmluops.map 之后，非global的符号，均被隐藏。
通过sample下的算子demo，测试加--version-script 选项 前后生成动态库，对demo运行的影响
- …
> [Feature](bangc-ops): fix libmluops.so file symbol visibility

- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
update proto and API comments for indice_convolution_backward_data
modify bangc-ops/mlu_op.h
modify bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
|        1       |Supported …
> [Feature](bangc-ops): update proto and API comments indices_convolution_backward_data

- .github/workflows/ci.yaml
For fast bangc code merging checking. Temporarily have bangpy test offline.
.github/workflow/ci.yaml
> [Fix](mlu-ops): Temporarily make bangpy test offline for bangc code merging test.

- bangc-ops/CMakeLists.txt
Modify the order of the CMakeList link library to resolve the link error reported in the single operator compilation of binary migration
- 修改 bangc-ops/CMakeList.txt 编译脚本 
- 问题描述：
1. 静态库libextops.a需要依赖core目录下的部分接口功能
2. 因之前符号隐藏方案的修改需要将bangc-ops/core目录下的源码，单独编译为静态库mluopscore.a，然后在link到mluops.so中，因先link了mluopscore，导致在单算子编译时，编译器将mluopscore不需要的符号没有完全link到mluops中，因此在之后链接libextops.a，报link错误，libextops.a库依赖的部分接口符号找不到（core目录下的接口）
- 解决方案：
1. 修改CMakeList，调整链接libmluopscore.a的位置，放在链接libextops.a之后链接
2. 链接mluopscore时，加上-Wl,--whole-archive 链接选项，将mluopscore的符号完全link到mluops.so中
- ./build.sh --filter="add_n" 通过
- 多系统测试：ubuntu18.04/20.04、centos7/8、Debian10 编译测试通过
> [Fix](bangc-ops): fix CMakeList.txt to resolve link error

- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
- docs/bangc-docs/design_docs/indice_convolution_backward_filter/indice_convolution_backward_filter.md
- docs/bangc-docs/user_guide/9_operators/index.rst
indice convolution backward filter文档类型修改
有以下几个改动
1. 头文件中group名称有误，改成了单算子的名称
2. proto文件中缺少空行
3. user guide的index.rst中，有个格式不对，修改一下
4. 头文件中有些行长度不对，用格式化工具刷了一下。
no, 不涉及功能修改
> [Docs](bangc-ops): fix spconv_bpfilter docs problem

- bangc-ops/kernels/indice_convolution_forward/indice_convolution_forward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_forward/indice_convolution_forward.cpp
~~Thanks for your contribution and we appreciate it a lot. ~~
Bug fix of foolproof of subM and inverse
/bangc-ops/kernels/indice_convolution_forward
/test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_forward
[ SUMMARY  ] Total 81 cases of 1 op(s).
ALL PASSED.
[==========] 81 test cases from 1 test suite ran. (14024 ms total)
[  PASSED  ] 81 test cases.
Fix bug of foolproof subM and inverse and test in newly added related test cases.
> [Fix](bangc-ops):fix indice_convolution_forward bug

- bangc-ops/kernels/get_indice_pairs/get_indice_pairs.cpp
- bangc-ops/kernels/get_indice_pairs/get_indice_pairs_block.mlu
- bangc-ops/kernels/get_indice_pairs/get_indice_pairs_utils.h
- bangc-ops/kernels/get_indice_pairs/normal_get_indice_pairs.cpp
- bangc-ops/kernels/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
- bangc-ops/mlu_op.h
- bangc-ops/mlu_op_kernel.h
> [Fix](bangc-ops) :fix get_indice_pairs bug

- bangc-ops/kernels/get_indice_pairs/get_indice_pairs.cpp
- bangc-ops/kernels/get_indice_pairs/get_indice_pairs_structs.cpp
- bangc-ops/kernels/get_indice_pairs/get_indice_pairs_structs.h
- bangc-ops/kernels/get_indice_pairs/normal_get_indice_pairs.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
> [Fix](bangc-ops) get num_act_out from sparse_conv_desc

- bangc-ops/kernels/indice_convolution_backward_data/indice_convolution_backward_data.cpp
- bangc-ops/mlu_op.h
- docs/bangc-docs/design_docs/indice_convolution_backward_data/indice_convolution_backward_data.md
Complete foolcheck.
When the value of \b sub_m is 1, the middle number of \b indice_num should be the maximum number of \b indice_num..
[2023-2-21 10:48:28] [MLUOP] [Error]:[mluOpIndiceConvolutionBackwardData] The middle number of the indice_num array should be the maximum of the array when sub_m is 1. Now the maximum is 116 while the middle number of the array is 44.
[2023-2-21 10:48:28] [MLUOP] [Error]:"MLUOP_STATUS_BAD_PARAM in mluOpIndiceConvolutionBackwardData( handle_, output_grad_desc, output_grad, filters_desc, filter, indice_pairs_desc, indice_pairs, indice_num_.data(), inverse_, sub_m_, workspace_[0], workspace_size, input_grad_desc, input_grad)"
> [Fix](bangc-ops): update foolcheck for indice_convolution_backward_data

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_backward/roi_align_rotated_backward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_forward/roi_align_rotated_forward.cpp
Fix roi_align_rotated cpu compute
1) bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_forward/roi_align_rotated_forward.cpp
2) bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_backward/roi_align_rotated_backward.cpp
|----------------|--------------------------------------|---- …
> [Fix](bangc-ops): fix roi_align_rotated cpu compute

- bangc-ops/kernels/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
防呆修改
- 补充两条漏掉的防呆，和头文件保持一致。
- gtest传参数修改
When a new operator is submitted, the test points are given and the test results are stated.
|                   Test Point                    | Acceptance Standard | Test Result (Error Message) |
| ----------------------------------------------- | --------------------| --------------------------- |
| inverse==0的检查 |     Normal error    |    [MLUOP] [Error]:[mluOpGetIndiceConvolutionBackwardFilterWorkspaceSize] Check failed: inverse == 0                         |
| indice_pairs参数检查           |     Normal error    |       [mluOpGetIndiceConvolutionBackwardFilterWorkspaceSize] Shape check failed! Now the shapes are features_desc[512,56], output_grad_desc[512,32], indice_pairs_desc[36,2,256], …
> [Fix](bangc-ops): fix indice_convolution_backward_filter param check

- bangc-ops/kernels/get_indice_pairs/normal_get_indice_pairs.h
- bangc-ops/mlu_op_kernel.h
调整 mlu_op_kernel.h 头文件结构，勿包含 get_indice_pairs 相关内容	
调整 mlu_op_kernel.h 头文件结构，勿包含 get_indice_pairs 相关内容	
[MLU Hardware Time      ]: 111 (us)
[MLU Interface Time     ]: 53.622 (us)
[MLU IO Efficiency      ]: 0.00988979
[MLU Compute Efficiency ]: 0.0145
[MLU Workspace Size     ]: 5.71098e+06 (Bytes)
[MLU TheoryOps          ]: 3.70829e+06 (Ops)
[MLU TheoryIOs          ]: 3.0351e+06 (Bytes)
[MLU ComputeForce       ]: 2.304e+12 (op/s)
[MLU IoBandWidth        ]: 2764.8 (GB/s)
[GPU Hardware Time      ]: -1 (us)
[GPU IO Efficiency      ]: -1
[GPU Compute Efficiency ]: -1
[GPU Workspace Size     ]: -1 (Bytes)
[Diffs]:
[output1]
DIFF3: 0.000000e+00
[output2]
DIFF3: 0.000000e+00
[output3]
DIFF3: 0.000000e+00
[^      OK ] …
> [Feature](bangc-ops) : adjust mlu_op_kernel.h

- bangc-ops/kernels/indice_convolution_forward/indice_convolution_forward.cpp
Add missing param check of data type and nullptr to indice_convolution_forward.
/mlu-ops/bangc-ops/kernels/indice_convolution_forward/ …
> [Fix](bangc-ops): add data type check, workspacesize nullptr check to indice_convolution_forward

- bangc-ops/kernels/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
修正防呆检查，之前的防呆检查写错了，导致正确的规模也会被防呆检查拦住。
应该检查indice_pairs的最后一个维度和features的第一个维度相同。下意识的搞成卷积里的ci了，写成了和ci进行检查。
When a new operator is submitted, the test points are given and the test results are stated.
|                   Test Point                    | Acceptance Standard | Test Result (Error Message) |
| ----------------------------------------------- | --------------------| --------------------------- |
| 　和第一个维度进行检查 |     Normal error    |    [MLUOP] [Error]:[mluOpGetIndiceConvolutionBackwardFilterWorkspaceSize] Shape check failed! Now the shapes are features_desc[512,256], output_grad_desc[512,32], indice_pairs_desc[36,2,256], and filters_grad_desc[2,3,6,256,32].      |
不涉及 …
> [Fix](bangc-ops): fix indice_convolution_backward_filter param check　

- bangc-ops/kernels/indice_convolution_forward/indice_convolution_forward.cpp
Place zero element before nullptr check to avoid error in zero element case.
/mlu-ops/bangc-ops/kernels/indice_convolution_forward/ …
> [Fix](bangc-ops): place indice_convolution_forward zero element before nullptr check

- bangc-ops/kernels/get_indice_pairs/get_indice_pairs.cpp
加入0元素防呆和workspace 防呆
加入0元素防呆和workspace 防呆
generator case 测试 
[MLU Hardware Time      ]: 112 (us)
[MLU Interface Time     ]: 75.338 (us)
[MLU IO Efficiency      ]: 0.00980148
[MLU Compute Efficiency ]: 0.0143705
[MLU Workspace Size     ]: 5.71098e+06 (Bytes)
[MLU TheoryOps          ]: 3.70829e+06 (Ops)
[MLU TheoryIOs          ]: 3.0351e+06 (Bytes)
[MLU ComputeForce       ]: 2.304e+12 (op/s)
[MLU IoBandWidth        ]: 2764.8 (GB/s)
[GPU Hardware Time      ]: -1 (us)
[GPU IO Efficiency      ]: -1
[GPU Compute Efficiency ]: -1
[GPU Workspace Size     ]: -1 (Bytes)
[Diffs]: …
> [Fix](bangc-ops) fix get indice pairs zero element

- bangc-ops/kernels/get_indice_pairs/get_indice_pairs.cpp
- bangc-ops/kernels/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
generator 大规模case 通过测试
[MLU Hardware Time ]: 114 (us)
[MLU Interface Time ]: 90.417 (us)
[MLU IO Efficiency ]: 0.0129999
[MLU Compute Efficiency ]: 0.0141184
[MLU Workspace Size ]: 5.71098e+06 (Bytes)
[MLU TheoryOps ]: 3.70829e+06 (Ops)
[MLU TheoryIOs ]: 3.0351e+06 (Bytes)
[MLU ComputeForce ]: 2.304e+12 (op/s)
[MLU IoBandWidth ]: 2048 (GB/s)
[GPU Hardware Time ]: -1 (us)
[GPU IO Efficiency ]: -1
[GPU Compute Efficiency ]: -1
[GPU Workspace Size ]: -1 (Bytes)
[Diffs]:
[output1]
DIFF3: 0.000000e+00
[output2]
DIFF3: 0.000000e+00 …
> [Feature](bangc-ops) Get indice pairs paltform 05

- bangc-ops/kernels/get_indice_pairs/get_indice_pairs.cpp
- bangc-ops/kernels/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
generator 大规模case 通过测试
[MLU Hardware Time      ]: 114 (us)
[MLU Interface Time     ]: 90.417 (us)
[MLU IO Efficiency      ]: 0.0129999
[MLU Compute Efficiency ]: 0.0141184
[MLU Workspace Size     ]: 5.71098e+06 (Bytes)
[MLU TheoryOps          ]: 3.70829e+06 (Ops)
[MLU TheoryIOs          ]: 3.0351e+06 (Bytes)
[MLU ComputeForce       ]: 2.304e+12 (op/s)
[MLU IoBandWidth        ]: 2048 (GB/s)
[GPU Hardware Time      ]: -1 (us)
[GPU IO Efficiency      ]: -1
[GPU Compute Efficiency ]: -1
[GPU Workspace Size     ]: -1 (Bytes) …
> [Feature](bangc-ops) add platform check

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_backward_filter/indice_convolution_backward_filter_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_backward_filter/indice_convolution_backward_filter_workspace.cpp
…dice_convolution_backward_filter
|----------------|--------------------------------------|----- …
> [TEST](indice_convolution_backward_filter):add api check cases for indice_convolution_backward_filter

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_forward/indice_convolution_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_forward/indice_convolution_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_forward/indice_convolution_forward_workspace.cpp
…volution_forward
|----------------|--------------------------------------|--------------------- …
> [TEST](indice_convolution_forward):add api check cases for indice_convolution_forward

- tools/coverage.sh
Revise coverage.sh to print operator only info.
modified:   tools/coverage.sh
> [Fix](bangc-ops): revise coverage.sh to print operator only info.

- bangc-ops/kernels/utils/common.h
- bangc-ops/kernels/voxelization/voxelization.cpp
- bangc-ops/kernels/voxelization/voxelization_kernel.mlu
Make voxelization operator supported mlu200 series.
mlu-ops/bangc-ops/kernels/voxelization/voxelization.cpp
mlu-ops/bangc-ops/kernels/voxelization/voxelization_kernel.mlu
mlu-ops/bangc-ops/kernels/utils/common.h
| No.  | Details                                | Check Results              |
| ---- | -------------------------------------- | -------------------------- |
| 1    | Supported hardware                     | MLU290<br>MLU370<br>MLU590 |
| 2    | Job types                              | block <br> U1              |
| 3    | Layouts …
> [Feature](bangc-ops): Make voxelization operator supported mlu200 series. 

- bangc-ops/CMakeLists.txt
- bangc-ops/README.md
- bangc-ops/core/cnlog.cpp
- bangc-ops/core/cnlog.h
- bangc-ops/core/context.cpp
- bangc-ops/core/gen_case.cpp
- bangc-ops/core/gen_case.h
- bangc-ops/core/logging.h
- bangc-ops/core/mlu_env.cpp
- bangc-ops/core/tensor.cpp
- bangc-ops/core/tool.cpp
- bangc-ops/core/tool.h
- bangc-ops/core/type.cpp
- bangc-ops/core/type.h
- bangc-ops/gen_symbol_visibility_map.py
- bangc-ops/independent_build.sh
- bangc-ops/kernels/ball_query/ball_query.mlu
- bangc-ops/kernels/binary_op/binary_op_host.cpp
- bangc-ops/kernels/copy/copy.cpp
- bangc-ops/kernels/expand/expand.cpp
- bangc-ops/kernels/fill/fill.cpp
- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.cpp
- bangc-ops/kernels/nms_rotated/nms_rotated.cpp
- bangc-ops/kernels/psamask/psamask.cpp
- bangc-ops/kernels/psroipool/psroipool.cpp
- bangc-ops/kernels/unary_op/unary_op_host.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/executor.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/parser.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/pb_test_tools.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/fill/fill.cpp
修改r0.4分支：
- bangc-ops下公共代码增加namespace
- 修改编译相关脚本，支持符号隐藏功能
modified:   bangc-ops/CMakeLists.txt
modified:   bangc-ops/README.md
modified:   bangc-ops/core/cnlog.cpp
modified:   bangc-ops/core/cnlog.h
modified:   bangc-ops/core/context.cpp
modified:   bangc-ops/core/gen_case.cpp
modified:   bangc-ops/core/gen_case.h
modified:   bangc-ops/core/logging.h
modified:   bangc-ops/core/mlu_env.cpp
modified:   bangc-ops/core/tensor.cpp
modified:   bangc-ops/core/tool.cpp
modified:   bangc-ops/core/tool.h
modified:   bangc-ops/core/type.cpp
modified:   bangc-ops/core/type.h
new file:   bangc-ops/gen_symbol_visibility_map.py
modified:   bangc-ops/independent_build.sh
modified:   bangc-ops/kernels/ball_query/ball_query.mlu
modified: …
> [Feature](bangc-ops): add namespace and symbol visibility

- bangc-ops/kernels/indice_convolution_backward_data/indice_convolution_backward_data.cpp
Complete the fool check that workspace_size should not be a nullptr in get-workspace-size API.
Modify: bangc-ops/kernels/indice_convolution_backward_data/indice_convolution_backward_data.cpp
No kernel function or host invoke logic is modified. So directly using CI as complete test.
Meanwhile, the workspace_size fool-check cannot be tested within google-test
> [Feature](bangc-ops): add foolcheck for indice-convbpdata workspace-size ptr

- bangc-ops/kernels/nms_rotated/nms_rotated.cpp
- bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
- docs/bangc-docs/design_docs/nms_rotated/nms_rotated.md
> [Fix] (bangc-ops): nms_rotated not support for large tensor

- bangc-ops/kernels/nms_rotated/nms_rotated.cpp
- bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
- docs/bangc-docs/design_docs/nms_rotated/nms_rotated.md
nms_rotated not support large tensor
|        1       |Supported hardware …
> [Fix](bangc-ops): nms_rotated not support for large tensor

- bangc-ops/kernel_depends.toml
Fix compile bug for carafe by adding op name in kernel_depends.toml.
modified: bangc-ops/kernel_depends.toml
> [Fix](bangc-ops): modify kernel_depends.toml of carafe.

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/daily.yaml
transfer ci to new local for r0.4.
modified:   .github/workflows/bangc_ci.yaml
modified:   .github/workflows/daily.yaml
> [Fix](bangc-ops): transfer ci to new local for r0.4.

- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/test_case/case_0.prototxt
Add gtest for MatMul kernel(binary kernel).
modified: bangc-ops/kernels/kernel_wrapper/lib/libextops.a
modified: bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
new file: bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.cpp
new file: bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.h
new file: bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/test_case/case_0.prototxt
Passed unit test.
> [Feature](bangc-ops): Add ops GTEST and upgrade binary ops

- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/test_case/case_0.prototxt
Add gtest for MatMul kernel(binary kernel).
modified: bangc-ops/kernels/kernel_wrapper/lib/libextops.a
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.cpp
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/matmul.h
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/matmul/test_case/case_0.prototxt
Passed unit test.
> [Feature](bangc-ops): Add matmul gtest and upgrade binary ops

- bangc-ops/kernels/get_indice_pairs/get_indice_pairs_block.mlu
- bangc-ops/kernels/get_indice_pairs/normal_get_indice_pairs.cpp
> [Featrue] (bangc-ops) use fillv3 op to fill -1 in host

- bangc-ops/kernels/get_indice_pairs/get_indice_pairs_block.mlu
- bangc-ops/kernels/get_indice_pairs/normal_get_indice_pairs.cpp
> [Feature](bangc-ops) : use fillv3 op to fill -1 in host 

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/nms_rotated/nms_rotated.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/nms_rotated/nms_rotated_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/nms_rotated/nms_rotated_workspace.cpp
Check api parameters
Add cases for api check
```
[----------] 3 tests from bad_scores_dtype_shape/nms_rotated_general (0 ms total)
[----------] 3 tests from bad_output_dtype_shape/nms_rotated_general
[ RUN      ] bad_output_dtype_shape/nms_rotated_general.api_test/0
[2023-3-14 14:44:23] [MLUOP] [Error]:[mluOpNmsRotated] Check failed: output_desc->dtype == MLUOP_DTYPE_INT32. 
[       OK ] bad_output_dtype_shape/nms_rotated_general.api_test/0 (0 ms)
[ RUN      ] bad_output_dtype_shape/nms_rotated_general.api_test/1
[2023-3-14 14:44:23] [MLUOP] [Error]:[mluOpNmsRotated] Check failed: boxes_desc->dims[0] == output_desc->dims[0]. 
[       OK ] bad_output_dtype_shape/nms_rotated_general.api_test/1 (0 ms)
[ RUN      ] …
```
> [TEST](bangc-ops): add nms_rotated api cases

- bangc-ops/kernels/moe_dispatch_backward_gate/moe_dispatch_backward_gate.cpp
修复 590M9上部分case 多次测试，概率性出现精度越界问题.
- moe_dispatch_backward_gate.cpp：修改任务策略函数
原因分析：policyFunc 策略函数实现存在问题，在MLU590M9（实际最大 core_num 为48）上通过getCoreNumOfJobLimitCapability() 接口获取的最大 max_core_num 为32，当 samples=36 时，判断 samples>max_core_num 条件成立，policyFunc 函数中会重新给 k_dim->x/y/z 赋值（x*y*z = 48），导致在主流程中执行时，判断samples > (x*y*z = 48) 为假，调用了 mluOpUnionKernelMoeDispatchBwdGate1 ，而 mluOpUnionKernelMoeDispatchBwdGate1 需要进行核间同步 __sync_all_ipu()，此时任务类型为U1（正确应为U8）导致核间同步存在问题，出现概率性的精度越界。
For static threshold standard details, see: [MLU-OPS Accuracy Acceptance …
> [Fix](bangc-ops): fix moe_backward_gate some case accuracy out of range

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/moe_dispatch_forward/moe_dispatch_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/moe_dispatch_forward/moe_dispatch_forward_general.cpp
> [TEST](bangc-ops): add api check for moe_dispatch_forward

- bangc-ops/mlu_op.h
- docs/bangc-docs/design_docs/moe_dispatch_forward/moe_dispatch_forward.md
修改算子接口说明和文档
mlu_ops.h: 将moe_dispatch_forward的接口注释将dispatch从`in`设置成`out`
docs/bangc-docs/design_docs/moe_dispatch_forward/moe_dispatch_forward.md： 设计文档将`不支持原位`改为`支持原位`
> [Fix](bangc-ops): fix the description of moe_dispatch_forward op

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/moe_dispatch_backward_gate/moe_dispatch_backward_gate.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/moe_dispatch_backward_gate/moe_dispatch_backward_gate_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/moe_dispatch_backward_gate/moe_dispatch_backward_gate_workspace.cpp
添加moe_dispatch_backward_gate算子的防呆测试
1.moe_dispatch_backward_gate.cpp文件：
- 检查描述符指针：handle、indices_desc、 locations_desc、input_desc、dispatch_desc、grad_gates_desc为空防呆；
- 检查指针：indices、locations、input、dispatch、grad_gates为空防呆
2.moe_dispatch_backward_gate_workspace.cpp文件：
- 检查handle、input_desc、workspace_size为空防呆
3.moe_dispatch_backward_gate_general.cpp文件：
- 对输入输出支持的 dtype、layout 以及 shape 进行防呆
- 0 元素检查防呆，VLOG(5)打印信息，返回MLUOP_STATUS_SUCCESS
- 对参数samples、capacity、hidden、num_experts值进行防呆
- large tensor防呆：对indices_desc、 locations_desc、input_desc、dispatch_desc、grad_gates_desc的检查
> [TEST](bangc-ops):add api check for moe_dispatch_backward_gate

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/indice_convolution_forward/indice_convolution_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/moe_dispatch_backward_data/moe_dispatch_backward_data.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/moe_dispatch_backward_data/moe_dispatch_backward_data_general.cpp
添加moe_dispatch_backard_data 防呆测例
1.moe_dispatch_backward_data.cpp文件：
- 检查描述符指针：handle、indices_desc、 locations_desc、input_desc、dispatch_desc、grad_gates_desc为空防呆；
- 检查指针：indices、locations、input、dispatch、grad_gates为空防呆
2.moe_dispatch_backward_data_general.cpp文件：
- 对输入输出支持的 dtype、layout 以及 shape 进行防呆
- 0 元素检查防呆，VLOG(5)打印信息，返回MLUOP_STATUS_SUCCESS
- 对参数samples、capacity、hidden、num_experts值进行防呆
- large tensor防呆：对indices_desc、 locations_desc、input_desc、dispatch_desc、grad_gates_desc的检查
3. 修正indice_convolution_forward、indice_convolution_backward_backward_filter dtype
> [TEST](bangc-ops):add moe_dispatch_backward_data api check cases

- bangc-ops/kernels/ball_query/ball_query.mlu
- bangc-ops/mlu_op.h
当前算子的性能和真值有关，在适配GEN_CASE时，应该使用GEN_CASE_DATA_REAL宏。
在mluops.h头文件中的@param[in] handle 描述中，把算子名写错了。
本次修改成了保存真值的GEN_CASE_DATA_REAL宏；纠正了在mluops.h中@param[in] handle 描述的错误算子名。
修改后的测试报告：https://wiki.cambricon.com/pages/viewpage.action?pageId=273646201
不涉及算子性能和精度
> [Fix](bangc-ops):fix ballquery gencase macro function

- bangc-ops/CMakeLists.txt
- bangc-ops/test/mlu_op_gtest/CMakeLists.txt
- r0.4分支出现单算子编译报 link error 问题：
> 修改编译脚本解决单算子编译 link error 问题，出错日志：
> ./build.sh --filter="abs"
../lib/libmluopscore.a(context.cpp.o): In function `mluOpCreate':
context.cpp:(.text+0x1119): undefined reference to `cnCtxGetCurrent'
context.cpp:(.text+0x1690): undefined reference to `cnCtxGetDevice'
context.cpp:(.text+0x183b): undefined reference to `cnSharedContextAcquire'
context.cpp:(.text+0x19ec): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1b96): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1d40): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1de6): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1e91): undefined reference to …
> [Fix](bangc-ops): r0.4 modify CMakeList to solve the single-operator link error

- bangc-ops/CMakeLists.txt
- bangc-ops/test/mlu_op_gtest/CMakeLists.txt
- r0.4分支出现单算子编译报 link error 问题 ，master因link extops.a 将该问题隐藏掉了，稳妥起见也修复下：
> 修改编译脚本解决单算子编译 link error 问题，出错日志：
> ./build.sh --filter="abs"
../lib/libmluopscore.a(context.cpp.o): In function `mluOpCreate':
context.cpp:(.text+0x1119): undefined reference to `cnCtxGetCurrent'
context.cpp:(.text+0x1690): undefined reference to `cnCtxGetDevice'
context.cpp:(.text+0x183b): undefined reference to `cnSharedContextAcquire'
context.cpp:(.text+0x19ec): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1b96): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1d40): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1de6): undefined reference to `cnDeviceGetAttribute'
context.cpp:(.text+0x1e91): …
> [Fix](bangc-ops):modify CMakeList to solve the single-operator link error

- bangc-ops/kernels/roi_crop/roi_crop_block.mlu
修改算子逻辑使其支持nan/inf的cases
1）modified:   bangc-ops/kernels/roi_crop/roi_crop_block.mlu
|        2       |Job …
> [Feature](bangc-ops):support nan/inf

- bangc-ops/kernels/roi_crop/roi_crop_block.mlu
- bangc-ops/mlu_op.h
修改算子逻辑，使其支持nan/inf
1) modified:   bangc-ops/kernels/roi_crop/roi_crop_block.mlu
|        2       |Job types …
> [Feature](bangc-ops):roi_crop_backward support nan/inf

- bangc-ops/independent_build.sh
r0.4 remove old install package when extract cntoolkit in independent_build.
bangc-ops/independent_build.sh
> [Fix](bangc-ops): r0.4 remove old install package when extract cntoolkit in independent_build.

- bangc-ops/independent_build.sh
r0.5 remove old install package when extract cntoolkit in independent_build.
bangc-ops/independent_build.sh
> [Fix](bangc-ops): r0.5 remove old install package when extract cntoolkit in independent_build.

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_crop_forward/roi_crop_forward.cpp
删除r0.4版本下，roi_crop_forward算子vlog打印部分的代码
1）modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_crop_forward/roi_crop_forward.cpp
> [Fix](bangc-ops):del roi_crop_forward some logs code

- .gitignore
- README.md
- bangc-ops/independent_build.sh
- bangc-ops/mlu_op.h
- tools/commitlint.py
- tools/coverage.sh
- tools/format2google
- tools/pre-commit
Sync independent build, libproto version restriction info, pre-commit and coverage test set up to master.
modified:   .gitignore
modified:   bangc-ops/independent_build.sh
modified:   tools/commitlint.py
modified:   tools/coverage.sh
modified:   tools/format2google
modified:   tools/pre-commit
all operators:
[ SUMMARY  ] Total 37 cases of 22 op(s).
ALL PASSED.
[==========] 37 test cases from 22 test suites ran. (8030 ms total)
[  PASSED  ] 37 test cases.
single op abs:
[ SUMMARY  ] Total 1 cases of 1 op(s).
ALL PASSED.
[==========] 1 test case from 1 test suite ran. (140 ms total)
[  PASSED  ] 1 test case.
coverage:  ball_query test
ilename …
> [Fix](bangc-ops): fix independent_build, libproto version info, pre-commit and coverage test.

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/get_indice_pairs/get_indice_pairs.cpp
fix  cpu code when in subm =1  mode 
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/get_indice_pairs/get_indice_pairs.cpp
jira:
http://jira.cambricon.com/browse/CNNLCORE-11555?filter=-1
|        1 …
> [Fix](bangc-ops) : fix subm=1 cpu

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roipoint_pool3d/roipoint_pool3d.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roipoint_pool3d/roipoint_pool3d_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roipoint_pool3d/roipoint_pool3d_workspace.cpp
添加roipoint_pool3d防呆测例
1.roipoint_pool3d.cpp文件：
检查描述符指针：handle、points_desc、 point_features_desc、boxes3d_desc、pooled_features_desc、pooled_empty_flag_desc为空防呆；
检查指针：points、point_features、boxes3d、workspace、pooled_features、pooled_empty_flag为空防呆
2.roipoint_pool3d_workspace.cpp文件：
检查描述符指针：handle、points_desc、 point_features_desc、boxes3d_desc、pooled_features_desc、pooled_empty_flag_desc为空防呆；
检查指针：size为空防呆
3.roipoint_pool3d_general.cpp文件：
对输入输出支持的 dtype、layout 以及 shape 进行防呆
0 元素检查防呆，VLOG(5)打印信息，返回MLUOP_STATUS_BAD_PARAM
large tensor防呆
> [TEST](bangc-ops):add roipoint_pool3d api check cases

- bangc-ops/kernels/ms_deform_attn_forward/ms_deform_attn_forward.mlu
- bangc-ops/kernels/ms_deform_attn_forward/msda_forward_fast_union1.mlu
- bangc-ops/kernels/ms_deform_attn_forward/msda_forward_small_channel_union1.mlu
- bangc-ops/kernels/ms_deform_attn_forward/msda_forward_union1_default.mlu
Temporarily fix a host selection error and fix device arch misleading.
modified:   kernels/ms_deform_attn_forward/ms_deform_attn_forward.mlu
modified:   kernels/ms_deform_attn_forward/msda_forward_fast_union1.mlu
modified:   kernels/ms_deform_attn_forward/msda_forward_small_channel_union1.mlu
Generate 8 cases and all passed.
[----------] 8 tests from ms_deform_attn_forward/TestSuite (32747 ms total)
[2023-4-7 15:37:2] [MLUOP] [Vlog]:TearDown CNRT environment.
[ SUMMARY  ] Total 8 cases of 1 op(s).
ALL PASSED.
[==========] 8 test cases from 1 test suite ran. (33171 ms total)
[  PASSED  ] 8 test cases.
Generate 23 cases and all passed.
[       OK ] …
> [Fix](bangc-ops): Fix a host selection error of ms_deform_attn_forward

- docs/bangc-docs/api_guide/update.rst
- docs/bangc-docs/release_notes/bangc_ops.rst
- docs/bangc-docs/user_guide/2_update_history/index.rst
- docs/bangc-docs/user_guide/9_operators/index.rst
change op name of roi_align_forward in docs
modified:   docs/bangc-docs/api_guide/update.rst
modified:   docs/bangc-docs/release_notes/bangc_ops.rst
modified:   docs/bangc-docs/user_guide/2_update_history/index.rst
modified:   docs/bangc-docs/user_guide/9_operators/index.rst
no test.
> [Fix](bangc-ops): change op name of roi_align_forward in docs

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_backward/carafe_backward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_backward/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_forward/carafe_forward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_forward/test_case/case_0.prototxt
合并carafe_forward和carafe_backward算子proto的param id;
bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_backward/carafe_backward.cpp
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_backward/test_case/case_0.prototxt
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_forward/carafe_forward.cpp
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/carafe_forward/test_case/case_0.prototxt
For static threshold standard details, see: [MLU-OPS Accuracy Acceptance Standard](https://github.com/Cambricon/mlu-ops/blob/master/docs/MLU-OP …
> [Fix](bangc-ops): unify carafe_forward and carafe_backward op's proto.

- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward.cpp
- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward.h
- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
- bangc-ops/kernels/ms_deform_attn_forward/ms_deform_attn_forward.mlu
- bangc-ops/kernels/ms_deform_attn_forward/ms_deform_attn_utils.h
- bangc-ops/kernels/ms_deform_attn_forward/msda_forward_fast_union1.mlu
Add optimized kernels for ms_deform_attn_forwrad/backwrad ops.
bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward.cpp
bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward.h
bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
bangc-ops/kernels/ms_deform_attn_forward/ms_deform_attn_forward.mlu
bangc-ops/kernels/ms_deform_attn_forward/ms_deform_attn_utils.h
bangc-ops/kernels/ms_deform_attn_forward/msda_forward_fast_union1.mlu
For static threshold standard details, see: [MLU-OPS Accuracy Acceptance …
> [Feature](bangc-ops): add ms_deform_attn_backward fast kernel

- bangc-ops/kernels/abs/abs_block.mlu
- bangc-ops/kernels/ball_query/ball_query_union1.mlu
- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_union1.mlu
- bangc-ops/kernels/div/div_block.mlu
- bangc-ops/kernels/log/log_block.mlu
- bangc-ops/kernels/sqrt/sqrt_block.mlu
- bangc-ops/kernels/three_interpolate_forward/three_interpolate_union1.mlu
r0.4 分支：修改.mlu 源文件中 MLULOG 为LOG(ERROR)
modified:   kernels/abs/abs_block.mlu
modified:   kernels/ball_query/ball_query_union1.mlu
modified:   kernels/box_iou_rotated/box_iou_rotated_union1.mlu
modified:   kernels/div/div_block.mlu
modified:   kernels/log/log_block.mlu
modified:   kernels/sqrt/sqrt_block.mlu
modified:   kernels/three_interpolate_forward/three_interpolate_union1.mlu
-  加 -d （debug）编译，全算子编译通过
> [Fix](bangc-ops): replace MLULOG to LOG(ERROR)

- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid.cpp
- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/focal_loss_sigmoid_backward/test_case/case_0.prototxt
- docs/bangc-docs/design_docs/focal_loss_sigmoid_backward/focal_loss_sigmoid_backward.md
improve focal_loss_sigmoid_backward precision by using supass inst
modified:   kernels/focal_loss_sigmoid/focal_loss_sigmoid.cpp
modified:   kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/focal_loss_sigmoid_backward/test_case/case_0.prototxt
|     No.        |                 Details              | …
> [Feature](bangc-ops): improve focal_loss_sigmoid_backward precision by using supass inst

- bangc-ops/kernels/mutual_information_backward/mutual_information_backward.cpp
- bangc-ops/kernels/mutual_information_backward/mutual_information_backward.h
- bangc-ops/kernels/mutual_information_backward/mutual_information_backward_block.mlu
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_backward/mutual_information_backward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_backward/mutual_information_backward.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_backward/test_case/mutual_information_backward.prototxt
- docs/bangc-docs/design_docs/mutual_information_backward/mutual_information_backward.md
- docs/bangc-docs/user_guide/9_operators/index.rst
add new_op, mutual_information_backward
```
new file:   bangc-ops/kernels/mutual_information_backward/mutual_information_backward.cpp
new file:   bangc-ops/kernels/mutual_information_backward/mutual_information_backward.h
new file:   bangc-ops/kernels/mutual_information_backward/mutual_information_backward_block.mlu
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_backward/mutual_information_backward.cpp
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_backward/mutual_information_backward.h
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_backward/test_case/mutual_information_backward.prototxt
new file: …
```
> [Feature](bangc-ops): add mutual_information_backward op

- bangc-ops/kernels/ball_query/ball_query.cpp
- bangc-ops/kernels/ball_query/ball_query.h
- bangc-ops/kernels/ball_query/ball_query_union1.mlu
…ar to 2G
支持元素数量略小于2G的情况
[^      OK ] /MLU_OPS/DEV_SOFT_TRAIN/wudongdong/benchmark_ball_query/ball_query/ball_query_20230406_16_05_19_391805_tid17782_device4.prototxt
[       OK ] ball_query/TestSuite.mluOp/11 (7 ms)
[----------] 12 tests from ball_query/TestSuite (1785 ms total)
[ SUMMARY  ] Total 12 cases of 1 op(s).
ALL PASSED.
[==========] 12 test cases from 1 test suite ran. (2523 ms total)
[  PASSED  ] 12 test cases.
[^      OK ] /MLU_OPS/DEV_SOFT_TRAIN/wudongdong/5_5_ball_query/default_platform/ball_query/ball_query_data_included_float16_int32_1683183034384.pb
[ …
> [Feature](bangc-ops):ball_query support the tensor num near to 2G

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/ms_deform_attn_forward/ms_deform_attn_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/ms_deform_attn_forward/ms_deform_attn_forward_general.cpp
> [TEST](bangc-ops): add ms_deform_attn_forward api test

- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward.cpp
add large tensor check
modified:   bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid.cpp
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward.cpp
tensor's element num near 2G 
370X4 & 590all
[^ OK ] /MLU_OPS/DEV_SOFT_TRAIN/wangyuan/wy_generator/mlu-ops-generator/generated_testcases/370_590/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward_data_split_int32_float16_1684137306623.pb
[ OK ] focal_loss_sigmoid_forward/TestSuite.mluOp/7 (78606 ms)
[----------] 6 tests from focal_loss_sigmoid_forward/TestSuite (816940 ms total)
[2023-5-15 16:15:23] [MLUOP] [Vlog]:TearDown CNRT environment.
[ SUMMARY ] Total 8 cases of 1 …
> [Feature](bangc-ops): add large tensor check

- bangc-ops/kernels/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
修复算子 reduce_type 防呆问题
1）modified:   bangc-ops/kernels/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
2）modified:   bangc-ops/mlu_op.h
3）modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.
[2023-5-17 10:39:37] [MLUOP] [Error]:[mluOpDynamicPointToVoxelForward]Only support max and mean. Please check reduce_type!
> [Fix](bangc-ops):fix dynamic_point_to_voxel_forward bug

- bangc-ops/kernels/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
修复算子 reduce_type 防呆问题
1）modified:   bangc-ops/kernels/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
2）modified:   bangc-ops/mlu_op.h
3）modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.
[2023-5-16 17:35:35] [MLUOP] [Error]:[mluOpDynamicPointToVoxelForward]Only support max and mean. Please check reduce_type!
> [Fix](bangc-ops): fix dynamic_point_to_voxel_forward bug

- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward.cpp
- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/ms_deform_attn_backward/ms_deform_attn_backward.cpp
Fix the bug of ms_deform_attn_backward op.
Converting floating point numbers to int is dangerous when the num larger than 16777215, tthis pull request is mainly change float computation to int, and fix the zero element bug.
Modification:
bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu  
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/ms_deform_attn_backward/ms_deform_attn_backward.cpp 
bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward.cpp
> [Fix](bangc-ops): fix ms_deform_attn_backward bug

- bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
This commit fixs the bug in nms_rotated op. The bug is caused by accessing a illegal address, which generated by the undefined behavior that  MPU manipulating the value  on the NRAM。
This commit restricts the memory access code only run in the right cores.
https://wiki.cambricon.com/pages/viewpage.action?pageId=299895716
> [Fix](bangc-ops): Fix nms_rotated bug

- bangc-ops/kernels/ball_query/ball_query_union1.mlu
- bangc-ops/kernels/bbox_overlaps/bbox_overlaps_union1.mlu
- bangc-ops/kernels/carafe/carafe_block.mlu
- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_union1.mlu
- bangc-ops/kernels/mutual_information_backward/mutual_information_backward_block.mlu
- bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d_union1.mlu
- bangc-ops/kernels/three_interpolate/three_interpolate_union1.mlu
- bangc-ops/kernels/utils/common.h
- bangc-ops/kernels/yolo_box/yolo_box_block.mlu
- docs/bangc-docs/design_docs/bbox_overlaps/bbox_overlaps.md
- docs/bangc-docs/design_docs/mutual_information_backward/mutual_information_backward.md
[Feature](bangc-ops): format func in common.h
modified:   bangc-ops/kernels/ball_query/ball_query_union1.mlu
modified:   bangc-ops/kernels/bbox_overlaps/bbox_overlaps_union1.mlu
modified:   bangc-ops/kernels/carafe/carafe_block.mlu
modified:   bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
modified:   bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
modified:   bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_union1.mlu
modified:   bangc-ops/kernels/mutual_information_backward/mutual_information_backward_block.mlu
modified:   bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d_union1.mlu
modified: …
> [Feature](bangc-ops): format func in common.h

- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
Fix focal_loss_sigmoid_backward mpu read overflow
modified: bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
(1) Accuracy pipeline:  http://jenkins.svc.cambricon.com/dist/job/MLUOPS/view/Pipelines-Adaptable/job/MLU_ALL_PLATFORMS/job/mluops_build_test_adaptable_mlu/84/
(2) Performance pipeline:  http://jenkins.svc.cambricon.com/dist/job/MLUOPS/view/Pipelines-Adaptable/job/MLU_ALL_PLATFORMS/job/mluops_build_perf_adaptable_mlu/64/
> [Fix](bangc-ops): Fix focal_loss_sigmoid_backward mpu read overflow

- bangc-ops/kernels/mutual_information_backward/mutual_information_backward_block.mlu
- bangc-ops/kernels/mutual_information_forward/mutual_information_forward.cpp
- bangc-ops/kernels/mutual_information_forward/mutual_information_forward.h
- bangc-ops/kernels/mutual_information_forward/mutual_information_forward_block.mlu
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_forward/mutual_information_forward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_forward/mutual_information_forward.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_forward/test_case/mutual_information_forward.prototxt
- docs/bangc-docs/design_docs/mutual_information_backward/mutual_information_backward.md
- docs/bangc-docs/design_docs/mutual_information_forward/mutual_information_forward.md
- docs/bangc-docs/user_guide/9_operators/index.rst
add new_op, mutual_information_forward
```
new file:   bangc-ops/kernels/mutual_information_forward/mutual_information_forward.cpp
new file:   bangc-ops/kernels/mutual_information_forward/mutual_information_forward.h
new file:   bangc-ops/kernels/mutual_information_forward/mutual_information_forward_block.mlu
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_forward/mutual_information_forward.cpp
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_forward/mutual_information_forward.h
new file:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/mutual_information_forward/test_case/mutual_information_forward.prototxt
new file:   docs/bangc-docs/design_docs/mutual_information_forward/mutual …
```
> [Feature](bangc-ops): add mutual_information_forward op

- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
Optimize the ms_deform_attn_backward op by using the new 3d-atomic interface.
bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
|        1       |Supported hardware                    |            MLU590         |
|        2       |Job types                             |          U1      |
|        3       |Layouts                               |          NCHW、ARRAY etc      |
|        4       |Whether multi-dimensions are supported|         NO                |
|        5       |Whether element zero is …
> [Perf](bangc-ops): Optimize ms_deform_attn_backward on MLU590

- bangc-ops/test/mlu_op_gtest/pb_gtest/gtest_config/test_list
- docs/bangc-docs/api_guide/update.rst
- docs/bangc-docs/release_notes/bangc_ops.rst
- docs/bangc-docs/user_guide/2_update_history/index.rst
correct release docs for v0.7.0
bangc-ops/test/mlu_op_gtest/pb_gtest/gtest_config/test_list b/bangc-ops/test/mlu_op_gtest/pb_gtest/gtest_config/test_list
docs/bangc-docs/api_guide/update.rst b/docs/bangc-docs/api_guide/update.rst
docs/bangc-docs/release_notes/bangc_ops.rst b/docs/bangc-docs/release_notes/bangc_ops.rst
docs/bangc-docs/user_guide/2_update_history/index.rst b/docs/bangc-docs/user_guide/2_update_history/index.rst
None.
> [Fix](bangc-ops): correct release docs for v0.7.0

- bangc-ops/test/mlu_op_gtest/pb_gtest/gtest_config/test_list
- docs/bangc-docs/api_guide/update.rst
- docs/bangc-docs/release_notes/bangc_ops.rst
- docs/bangc-docs/user_guide/2_update_history/index.rst
Delete masked_col2im_forward docs information
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/gtest_config/test_list
modified:   docs/bangc-docs/api_guide/update.rst
modified:   docs/bangc-docs/release_notes/bangc_ops.rst
modified:   docs/bangc-docs/user_guide/2_update_history/index.rst
None
> [Fix](bangc-ops): Delete masked_col2im_forward docs information

- .gitignore
- bangc-ops/CMakeLists.txt
Update clang version.
bangc-ops/CMakelist.txt
.gitignore
three_nn_forward test
filename [Sort by name]     Line Coverage [Sort_by_line     Functions [Sort_by
coverage]                       function_coverage]
three_nn_forward_union1.mlu [100.0%] 100.0 %314 /314  100.0 %22 / 22
Generated by: LCOV_version_1.14
> [Fix](bangc-ops): update clang version to fix coverage test on r0.7.

- .gitignore
- bangc-ops/CMakeLists.txt
Update clang version.
bangc-ops/CMakelist.txt
.gitignore
three_nn_forward test
filename [Sort by name]     Line Coverage [Sort_by_line     Functions [Sort_by
coverage]                       function_coverage]
three_nn_forward_union1.mlu [100.0%] 100.0 %314 /314  100.0 %22 / 22
Generated by: LCOV_version_1.14
> [Fix](bangc-ops): update clang version for coverage test.

- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid.cpp
- bangc-ops/mlu_op.h
fix focal_loss_sigmoid_backward gamma range precheck
modified:   kernels/focal_loss_sigmoid/focal_loss_sigmoid.cpp
（1） gamma test
[2023-6-1 15:37:59] [MLUOP] [Error]:[mluOpFocalLossSigmoidBackward]: gamma should be in the range of [0, 10000]. But now gamma is 20000.
[2023-6-1 15:37:59] [MLUOP] [Error]:"MLUOP_STATUS_NOT_SUPPORTED in mluOpFocalLossSigmoidBackward( handle_, prefer, reduction, input_desc, input_mlu, target_desc, target_mlu, weight_desc, weight_mlu, alpha, gamma, grad_input_desc, grad_input_mlu)"
(2) release_temp cases test
[^      OK ] /MLU_OPS/SOFT_TRAIN/release_temp/focal_loss_sigmoid_backward/focal_loss_sigmoid_backward_data_included_int32_float16_1682494108948.pb
[       OK ] …
> [Fix](bangc-ops): fix focal_loss_sigmoid_backward gamma range precheck

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/kl_test.cpp
include <math.h> + 低版本gcc编译下，abs(double(a))会报错abs函数二义性，这是由于math.h中的abs()仅适用于整数类型，如果想要获取double，则应使用fabs，由于仓库是C++标准，更改为cmath更合适一些.
> [Feature](bangc-ops): replace math.h by cmath

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
[Feature](bangc-ops): fix memory leak
[Please briefly describe what modification is made in this pull request, and indicate where to make the modification.](modified:   ../test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp) …
> [Fix](bangc-ops): fix memory leak

- tools/check_file_name.py
- tools/pre-commit
In directory bangc-ops/kernels/*/, .cpp and .mlu cannot be the same name.
- Add new file : tools/check_file_name.py
- Modify tools/pre-commit.
If abs.cpp and abs.mlu exist in bangc-ops/kernels/abs, it will be reported while pre-commit.
-- [check_file_name] Using tools/check_file_name.py to check the file_name
-- [check_file_name error] find abs.cpp and abs.mlu in directory bangc-ops/kernels/abs, the same name is forbidden.
> [Feature](bangc-ops):add file name format check

- bangc-ops/kernels/prior_box/prior_box_block.mlu
prior_box support nan/inf case.
bangc-ops/kernels/prior_box/prior_box_block.mlu
|        2       |Job types …
> [Feature](bangc-ops):prior_box support nan/inf.

- bangc-ops/kernels/voxelization/voxelization.cpp
- bangc-ops/kernels/voxelization/voxelization_kernel.mlu
support nan/inf case.
bangc-ops/kernels/voxelization/voxelization.cpp
bangc-ops/kernels/voxelization/voxelization_kernel.mlu …
> [Feature](bangc-ops):voxelization support nan/inf.

- bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
- bangc-ops/kernels/nms_rotated/nms_utils.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/nms_rotated/nms_rotated.cpp
- docs/bangc-docs/design_docs/nms_rotated/nms_rotated.md
boxes tensor support naninf
1. modified:   bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
2. modified:   bangc-ops/kernels/bangc-ops/kernels/nms_rotated/nms_utils.h
3. modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/nms_rotated/nms_rotated.cpp
4. modified:   docs/bangc-docs/design_docs/nms_rotated/nms_rotated.md
|     No.        |                 Details              | …
> [Feature](bangc-ops): nms_rotated boxes support naninf

- tools/check_log_error.py
fix space error in tools/check_log_error.
tools/check_log_error.py
> [Fix](bangc-ops): fix check_log_error space error.

- bangc-ops/kernels/deform_roi_pool/deform_roi_pool_union1.mlu
rois and offset support nan\inf.
- bangc-ops/kernels/deform_roi_pool/deform_roi_pool_union1.mlu
[ SUMMARY  ] Total 70 cases of 2 op(s).
ALL PASSED.
[==========] 70 test cases from 2 test suites ran. (19188 ms total)
[  PASSED  ] 70 test cases.
rois 支持 nan，rois 不支持 inf，当 roi 坐标为 inf 时，将产生 0~2147483647 的 for 循环；offset 支持 nan or inf.
> [Feature](bangc-ops): rois and offset support nan inf

- bangc-ops/kernels/bbox_overlaps/bbox_overlaps_union1.mlu
- docs/bangc-docs/design_docs/bbox_overlaps/bbox_overlaps.md
bbox_overlaps supports  large tensor test.
docs/bangc-docs/design_docs/bbox_overlaps/bbox_overlaps.md
bangc-ops/kernels/bbox_overlaps/bbox_overlaps_union1.mlu
|        1       |Supported hardware …
> [Feature](bangc-ops):bbox_overlaps opt

- bangc-ops/CMakeLists.txt
- bangc-ops/independent_build.sh
- docs/GTest-User-Guide-zh.md
Add BANG memcheck to check device memory.
- bangc-ops/CMakeLists.txt
- bangc-ops/independent_build.sh
- docs/GTest-User-Guide-zh.md
Will detect the Buffer Overflow on device
> [Feature](bangc-ops): Add bang memcheck

- bangc-ops/mlu_op.h
Correct the scale limitation of masked_im2col_forward.
- bangc-ops/mlu_op.h
> [Feature](bangc-ops):Correct the scale limitation

- bangc-ops/core/logging.h
- bangc-ops/kernels/get_indice_pairs/get_indice_pairs.cpp
- bangc-ops/kernels/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
> [Feature](bangc-ops): add fool-check for tensor size

- bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
fix buffer overflow detected warning when build with --enable-memcheck　
bangc-ops/kernels/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
> [Fix](bangc-ops):ms_deform_attn_backward memcheck warning fix.

- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_aligned.h
- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_nonaligned.h
- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_utils.h
Fix device memory leak.
modified:   bangc-ops/kernels/box_iou_rotated/box_iou_rotated_aligned.h
modified:   bangc-ops/kernels/box_iou_rotated/box_iou_rotated_nonaligned.h
modified:   bangc-ops/kernels/box_iou_rotated/box_iou_rotated_utils.h
--enable-bang-memcheck: no warning or  error
Platform：MLU370
release_temp: 108 cases passed.
release_test: 21 cases passed.
nan_inf case: 80 cases passed.
Platform：MLU590
release_temp: 108 cases passed.
release_test: 21 cases passed.
nan_inf case: 80 cases passed.
jenkins job 执行结果:
build status: SUCCESS
All test passed.
> [Fix](bangc-ops): fix device memory leak of box_iou_rotated.

- bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
- bangc-ops/kernels/nms_rotated/nms_utils.h
fix buffer overflow detected warning when build with --enable-memcheck
modified: bangc-ops/kernels/nms_rotated/nms_utils.h
modified: bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
--enable-bang-memcheck: no warning or error
Platform : MLU370
[ SUMMARY  ] Total 18 cases of 1 op(s).
ALL PASSED.
[==========] 18 test cases from 1 test suite ran. (27123 ms total)
[  PASSED  ] 18 test cases.
Platform : MLU590
[ SUMMARY  ] Total 18 cases of 1 op(s).
ALL PASSED.
[==========] 18 test cases from 1 test suite ran. (18350 ms total)
[  PASSED  ] 18 test cases.
jenkins job : SUCCESS
All test passed.
> [Fix](bangc-ops):fix mmcheck warning for nms_rotated

- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_forward_union1.mlu
- docs/bangc-docs/design_docs/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward.md
fix focal_loss nan,inf bug
modified:   bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_forward_union1.mlu
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/include/evaluator.h
modified:   docs/bangc-docs/design_docs/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward.md
None
release temp & benchmark, 370 & 590 all pass
benchmark 
HIGH_PRECISION VS HIGH_PRECISION(old version )，370 & 590 修复后版本性能下降7%-17%
MLUOP_COMPUTATION_FAST VS HIGH_PRECISION(old version )，370 & 590 性能提升10%-30%
> [Fix](bangc-ops): fix focal_loss nan,inf bug

- bangc-ops/mlu_op.h
mluOpRoipointPool3dForward，mluOpActiveRotatedFilterForward, mluOpThreeNNforward, mluOpPsamaskForward, mluOpPsamaskBackward, mluOpBoxIouRotated, mluOpDiffIouRotatedSortVerticesForward 接口返回值描述修改，其他算子缺少  MLUOP_STATUS_EXECUTION_FAILED 的进行统一添加
bangc-ops/mlu_op.h
> [Fix](bangc-ops): fix roipointpool3d interface description error.

- bangc-ops/mlu_op.h
delete unused api return message MLUOP_STATUS_INTERNAL_ERROR on indice_convolution_backward_data api
No test
> [Fix](bangc-ops): delete unused api return message on indice_convolution_backward_data api

- bangc-ops/kernels/roipoint_pool3d/roipoint_pool3d_union1_large_boxes_num.mlu
Fix device buffer overflow.
bangc-ops/kernels/roipoint_pool3d/roipoint_pool3d_union1_large_boxes_num.mlu
jenkins job 执行结果:
build status: SUCCESS
jobId 157
590 34 cases passed
370 34 cases passed
> [Fix](bangc-ops): fix roipoint_pool3d device memcheck buffer overflow.

- bangc-ops/kernels/voxel_pooling_forward/voxel_pooling_forward_union1.mlu
…ng coverage.
Repair the problem of gdram memory reading and writing coverage.
bangc-ops/kernels/voxel_pooling_forward/voxel_pooling_forward_union1.mlu
> [Fix](bangc-ops):Repair the problem of gdram memory reading and writing coverage.

- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
对于half类型测例，在片上转为float计算，nram偏移大小有误，存在内存越界风险。
modified: bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
精度流水：http://jenkins.svc.cambricon.com/dist/job/MLUOPS/view/Pipelines-Adaptable/job/MLU_ALL_PLATFORMS/job/mluops_build_test_adaptable_mlu/158/
性能流水： http://jenkins.svc.cambricon.com/dist/job/MLUOPS/view/Pipelines-Adaptable/job/MLU_ALL_PLATFORMS/job/mluops_build_perf_adaptable_mlu/113/
开启--enable-bang-memcheck编译，运行测例无Buffer Overflow Detected报错
> [Fix](bangc-ops): fix focalLossSigmoidBackward buffer overflow

- bangc-ops/kernels/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward_union1.mlu
fix memory leak of dynamic_point_to_voxel_backward caused by Implicit conversion
modified: bangc-ops/kernels/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward_union1.mlu
--enable-bang-memcheck: no warning or error
Platform : MLU370
[----------] 53 tests from dynamic_point_to_voxel_backward/TestSuite (171181 ms total)
[ SUMMARY  ] Total 53 cases of 1 op(s).
ALL PASSED.
[==========] 53 test cases from 1 test suite ran. (171675 ms total)
[  PASSED  ] 53 test cases.
Platform : MLU590
[----------] 51 tests from dynamic_point_to_voxel_backward/TestSuite (7879 ms total)
[ SUMMARY  ] Total 51 cases of 1 op(s).
ALL PASSED.
[==========] 51 test cases from 1 test suite ran. (8240 ms total)
[ …
> [Fix](bangc-ops): fix memory leak of dynamic_point_to_voxel_backward

- bangc-ops/kernels/prior_box/prior_box.cpp
Fix 500 series platform max_num_priors exceed the limit problem.
bangc-ops/kernels/prior_box/prior_box.cpp
> [Fix](bangc-ops):Fix 500 series platform max_num_priors exceed the limit problem.

- bangc-ops/kernels/bbox_overlaps/bbox_overlaps.cpp
- bangc-ops/kernels/bbox_overlaps/bbox_overlaps.h
- bangc-ops/kernels/bbox_overlaps/bbox_overlaps_union1.mlu
Support half data nan/inf.
modified:   bangc-ops/kernels/bbox_overlaps/bbox_overlaps.cpp
modified:   bangc-ops/kernels/bbox_overlaps/bbox_overlaps.h
modified:   bangc-ops/kernels/bbox_overlaps/bbox_overlaps_union1.mlu
370 & 590:
release_temp: 3502 cases paseed
release_test: 140 cases paseed
new half_nan_inf_case: 591 cases passed
All test passed.
> [Fix](bangc-ops): support half datatype nan/inf.

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/daily.yaml
- bangc-ops/mlu_op.h
- build.property
Update toolkit version to 3.6.0
modified:   bangc_all_system_ci.yaml
modified:   bangc_ci.yaml
modified:   daily.yaml
modified:   ../../bangc-ops/mlu_op.h
modified:   ../../build.property
See pipeline result.
> [Feature](bangc-ops): Update toolkit version to 3.6.0

- bangc-ops/kernels/bbox_overlaps/bbox_overlaps.cpp
add large tensor num check for bbox_overlaps.
bangc-ops/kernels/bbox_overlaps/bbox_overlaps.cpp
When a new operator is submitted, the test points are given and the test results are stated.
|                   Test Point                    | Acceptance Standard | Test Result (Error Message) |
| ----------------------------------------------- | --------------------| --------------------------- |
| input1 large tensor|    MLUOP_STATUS_NOT_SUPPORTED   |    MLUOP_STATUS_NOT_SUPPORTED                         |
| input2 large tensor|     MLUOP_STATUS_NOT_SUPPORTED   |    MLUOP_STATUS_NOT_SUPPORTED    |
| output large tensor|     "MLUOP_STATUS_NOT_SUPPORTED    |    "MLUOP_STATUS_NOT_SUPPORTED      |  
370 & 590:
release_temp: 3502 cases …
> [Fix](bangc-ops): add large tensor num check for bbox_overlaps.

- bangc-ops/kernels/abs/abs_block.mlu
- bangc-ops/kernels/bbox_overlaps/bbox_overlaps_union1.mlu
- bangc-ops/kernels/border_align_backward/border_align_backward_union1.mlu
- bangc-ops/kernels/border_align_forward/border_align_forward_union1.mlu
- bangc-ops/kernels/kernel.h
- bangc-ops/kernels/log/log.cpp
- bangc-ops/kernels/log/log.h
- bangc-ops/kernels/log/log_block.mlu
- bangc-ops/kernels/sqrt/sqrt.cpp
- bangc-ops/kernels/sqrt/sqrt.h
- bangc-ops/kernels/sqrt/sqrt_block.mlu
- bangc-ops/kernels/utils/common.h
modified:   bangc-ops/kernels/abs/abs_block.mlu
modified:   bangc-ops/kernels/kernel.h
modified:   bangc-ops/kernels/log/log.cpp
modified:   bangc-ops/kernels/log/log.h
modified:   bangc-ops/kernels/log/log_block.mlu
modified:   bangc-ops/kernels/sqrt/sqrt.cpp
modified:   bangc-ops/kernels/sqrt/sqrt.h
modified:   bangc-ops/kernels/sqrt/sqrt_block.mlu
modified:   bangc-ops/kernels/utils/common.h
370 & 590 all，--mode op --ops sqrt,log,abs --ops_limit_ratio 1 --limit_num 10
All pass
> [Feature](bangc-ops): Redefine sizeof in mlu file

- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/kernels/roi_pooling_forward/roi_pooling_forward.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_forward/roi_pooling_forward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_forward/roi_pooling_forward.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_forward/test_case/case_0.prototxt
- docs/bangc-docs/user_guide/9_operators/index.rst
Add new op roi_pooling_forward.
create bangc-ops/kernels/roi_pooling_forward/roi_pooling_forward.cpp
create bangc-ops//test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_forward/roi_pooling_forward.cpp
create bangc-ops//test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_forward/roi_pooling_forward.h
create bangc-ops//test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_forward/test_case/case_0.prototxt
change bangc-ops/mlu_op.h
change docs/bangc-docs/user_guide/9_operators/index.rst
change bangc-ops/kernels/kernel_wrapper/lib/libextops.a
change bangc-ops/kernels/kernel_wrapper/wrapper.h …
> [Feature](bangc-ops): new op roi_pooling_forward

- bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
fix warnings(address space doesn't match) when compiling nms_rotated.
modified: bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
Platform：MLU370
[----------] 18 tests from nms_rotated/TestSuite (22808 ms total)
[ SUMMARY  ] Total 18 cases of 1 op(s).
ALL PASSED.
[==========] 18 test cases from 1 test suite ran. (23423 ms total)
[  PASSED  ] 18 test cases.
Platform：MLU590
[----------] 18 tests from nms_rotated/TestSuite (15098 ms total)
[ SUMMARY  ] Total 18 cases of 1 op(s).
ALL PASSED.
[==========] 18 test cases from 1 test suite ran. (15736 ms total)
[  PASSED  ] 18 test cases.
Platform：MLU370-S4
Platform：MLU370-X4
Platform：MLU370-X8
Platform：MLU590-H8
Platform：MLU590-M9
All tests passed.
> [Fix](bangc-ops): fix warnings when compiling nms_rotated

- bangc-ops/kernels/psamask/psamask.cpp
add large tensor num check for psamask.
modified:   bangc-ops/kernels/psamask/psamask.cpp
the test points are given and the test results are stated.
|                   Test Point                    | Acceptance Standard | Test Result (Error Message) |
| ----------------------------------------------- | --------------------| --------------------------- |
| Large tensor check <br>inputs : "shape":[1,1,2,2147483640]       |     Normal error    |[2023-8-23 15:5:6] [MLUOP] [Error]:[mluOpPsamaskForward] Overflow max tensor num. Currently, MLU-OPS supports tensor num smaller than 2^31. <br>[2023-8-23 15:5:6] [MLUOP] [Error]:"MLUOP_STATUS_BAD_PARAM in mluOpPsamaskForward(handle_, psa_type, input_desc, input, h_mask, w_mask, output_desc, …
> [Fix](bangc-ops): add large tensor num check for psamask.

- docs/bangc-docs/user_guide/11_env_var/index.rst
fix env var guide link error
docs/bangc-docs/user_guide/11_env_var/index.rst
no test.
> [Docs](bangc-ops): fix env var guide link error.

- bangc-ops/independent_build.sh
Clear build/mlu_op_gtest when build mlu-ops.
bangc-ops/independent_build.sh
> [Fix](bangc-ops): clear build/mlu_op_gtest when build.

- bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
- bangc-ops/mlu_op.h
nms_rotated fix code of iou_threshold<0 cases
1. modified:   bangc-ops/kernels/nms_rotated/nms_rotated_union1.mlu
|        1       |Supported hardware                    |          MLU370<br>MLU590 …
> [Feature](bangc-ops): nms_rotated fix code of iou_threshold<0 cases

- bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d.cpp
- bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d_union1.mlu
- bangc-ops/mlu_op.h
MMCV中存在隐含的限制条件，在host端新增相应的参数检查。
- dim3结构体，限制了boxes_num和channels大小。
- pts_mask指针的最大偏移值为 boxes_num * pts_num，它们均为int类型。
sin/cos指令精度与竞品不对齐。
nram_max_pts_feature_tmp该内存空间未使用过。
a.**mlu-ops/bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d.cpp**中 
- boxes_num < 65536
- channels < 65536
- product of boxes_num and pts_num < 2^31
b.**mlu-ops/bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d_union1.mlu**中
- delete unused memory (nram_max_pts_feature_tmp)
- __cn_scalar_sin_* replace std::sin;__cn_scalar_cos_* replace std::cos
c.**mlu-ops/bangc-ops/mlu_op.h**中
-增加参数限制的注释 …
> [Fix](bangc-ops): roiaware add Param Check and use __cn_scalar_sin_*

- bangc-ops/mlu_op.h
- docs/bangc-docs/design_docs/roiaware_pool3d_backward/roiaware_pool3d_backward.md
- docs/bangc-docs/design_docs/roiaware_pool3d_forward/roiaware_pool3d_forward.md
roiaware_pool3d的mlu_op.h和文档需要修改
mlu-ops/bangc-ops/mlu_op.h 增加 roiaware_pool3d_backward的注释
mlu-ops/docs/bangc-docs/design_docs/roiaware_pool3d_forward/roiaware_pool3d_forward.md 和
mlu-ops/docs/bangc-docs/design_docs/roiaware_pool3d_backward/roiaware_pool3d_backward.md中
有符号错误，应该用乘号替换。
- Job types
MLU370 and MLU590 all pass.
> [Fix](bangc-ops): roiaware add annotation and modify docs

- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/kernels/sync_batch_norm_backward_elemt/sync_batch_norm_backward_elemt.cpp
- bangc-ops/kernels/sync_batchnorm_backward_elemt_v2/sync_batchnorm_backward_elemt_v2.cpp
- bangc-ops/kernels/sync_batchnorm_backward_reduce/sync_batchnorm_backward_reduce.cpp
- bangc-ops/kernels/sync_batchnorm_elemt/sync_batchnorm_elemt.cpp
- bangc-ops/kernels/sync_batchnorm_gather_stats_with_counts/sync_batchnorm_gather_stats_with_counts.cpp
- bangc-ops/kernels/sync_batchnorm_stats/sync_batchnorm_stats.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batch_norm_backward_elemt/sync_batch_norm_backward_elemt.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batch_norm_backward_elemt/sync_batch_norm_backward_elemt.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batch_norm_backward_elemt/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_backward_elemt_v2/sync_batchnorm_backward_elemt_v2.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_backward_elemt_v2/sync_batchnorm_backward_elemt_v2.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_backward_elemt_v2/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_backward_reduce/sync_batchnorm_backward_reduce.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_backward_reduce/sync_batchnorm_backward_reduce.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_backward_reduce/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_elemt/sync_batchnorm_elemt.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_elemt/sync_batchnorm_elemt.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_elemt/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_gather_stats_with_counts/sync_batchnorm_gather_stats_with_counts.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_gather_stats_with_counts/sync_batchnorm_gather_stats_with_counts.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_gather_stats_with_counts/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_gather_stats_with_counts/test_case/case_1.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_gather_stats_with_counts/test_case/case_2.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_stats/sync_batchnorm_stats.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_stats/sync_batchnorm_stats.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_stats/test_case/case_0.prototxt
- docs/bangc-docs/user_guide/9_operators/index.rst
将sybn6个小算子以二进制形式合入mluops。
增加算子sync_batch_norm_backward_elemt，sync_batchnorm_backward_elemt_v2，sync_batchnorm_backward_reduce，
sync_batchnorm_elemt，sync_batchnorm_gather_stats_with_counts，sync_batchnorm_stats。
- diff1
- diff2
- Job types
Test Point-1: `When a new operator is …
> [Feature](bangc-ops): add Sybn op.

- bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d.cpp
- bangc-ops/mlu_op.h
Limitation中有max_pts_each_voxel参数防呆，将这个防呆加到host端中
mlu-ops/banc-ops/mlu_op.h 增加max_pts_each_voxel参数说明
mlu-ops/bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d.cpp 增加max_pts_each_voxel防呆
> [Feature](bangc-ops): roiaware_pool3d add max_pts_each_voxel paramcheck

- bangc-ops/kernels/roiaware_pool3d/roiaware_pool3d.cpp
规范防呆相关代码.
- 调用mluops其他算子应使用MLUOP_CHECK。
- 对宏定义变量的PARAM_CHECK重新改写。
原因：宏定义的变量（如：THRESHOLD_OF_BOXES_NUM_AND_CHANNELS），
使用PARAM_CHECK时，LOG信息只显示字符串，不具备自解释性。
- 调用函数（如：transposeTensor），在函数内部输出LOG。
> [Feature](bangc-ops):Roiaware_pool3d specify 'paramcheck'

- bangc-ops/kernels/box_iou_rotated/box_iou_rotated.cpp
add maximum input size check for box_iou_rotated
bangc-ops/kernels/box_iou_rotated/box_iou_rotated.cpp
- diff1
- diff2
- diff3
skip
skip
```bash …
```
> [Feature](bangc-ops): add maximum input size check for box_iou_rotated.

- bangc-ops/kernels/poly_nms/poly_nms.cpp
- bangc-ops/mlu_op.h
fix polynms descriptor.
bangc-ops/mlu_op.h
bangc-ops/kernels/poly_nms/poly_nms.cpp
> [Fix](mlu-ops):fix polynms doc's descriptor.

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_1.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_2.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_3.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_4.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_5.prototxt
delete op_type in cpu cases of pad operator
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_0.prototxt
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_1.prototxt
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_2.prototxt
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_3.prototxt
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_4.prototxt
modified:   bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_5.prototxt …
> [TEST](bangc-ops): Delete op_type in cpu cases of pad operator

- bangc-ops/kernels/concat/concat.cpp
- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/concat/concat.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/concat/concat.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/concat/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/concat/test_case/case_1.prototxt
- docs/bangc-docs/user_guide/9_operators/index.rst
将concat算子以二进制形式合入mluops
增加concat算子
- diff3
```bash
Please fill your test results(Error Message) in here, ...
```
Test Point-2: …
> [Feature](bangc-ops): add concat binary operator.

- bangc-ops/mlu_op.h
modify MLUOP and MLU to MLU-OPS in mlu_op.h handle part
> [Docs](bangc-ops): modify MLUOP to MLU-OPS in mlu_op.h handle part

- bangc-ops/.gitattributes
- bangc-ops/kernels/batch_matmul_bcast/batch_matmul_bcast.cpp
- bangc-ops/kernels/kernel_wrapper/lib/libextops.a
- bangc-ops/kernels/kernel_wrapper/lib/libextops_0.a
- bangc-ops/kernels/kernel_wrapper/lib/libextops_1.a
- bangc-ops/kernels/kernel_wrapper/lib/libextops_2.a
- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/include/executor.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/batch_matmul_bcast/batch_matmul_bcast.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/batch_matmul_bcast/batch_matmul_bcast.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/batch_matmul_bcast/test_case/case_0.prototxt
将batch_matmul_bcast算子以二进制形式合入mluops。
增加batch_matmul_bcast算子
- diff1
- diff2
- Job types
Test Point-1: `When a new operator is submitted, the test points are given and the test results are stated`. …
> [feature](bangc-ops):add batch_matmul_bcast

- docs/bangc-docs/api_guide/update.rst
修复开发手册格式问题。
modified:   docs/bangc-docs/api_guide/update.rst
> [Docs](bangc-ops): fix developer guide format problem

- docs/bangc-docs/api_guide/update.rst
修复开发手册格式问题。
modified: docs/bangc-docs/api_guide/update.rst
> [Docs](bangc-ops): fix developer guide format

- bangc-ops/kernels/dcn_backward_data/dcn_backward_data.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/pb_test_tools.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/test_case/case0.prototxt
- docs/bangc-docs/BANGC-OPS-OpList.md
- docs/bangc-docs/user_guide/9_operators/index.rst
Add new binary-op mluOpDCNBackwardData.
bangc-ops/kernels/dcn_backward_data/dcn_backward_data.cpp
bangc-ops/mlu_op.h
bangc-ops/test/mlu_op_gtest/pb_gtest/src/pb_test_tools.cpp
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.cpp
bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.h
docs/bangc-docs/BANGC-OPS-OpList.md
- …
> [Feature](bangc-ops): Add new binary op mluOpDCNBackwardData.

- kernels/utils/cnnl_helper.cpp
Add more info to CALL_CNNL MACRO
kernels/utils/cnnl_helper.cpp
if error occurred, it show like following:
take three_nn_forward for example.
[2024-1-10 14:49:32] [CNNL] [Error]:[cnnlSetTransposeDescriptor] Check failed: desc != NULL. 
[2024-1-10 14:49:32] [MLUOP] [Error]:CNNL_HELPER: Internal cnnl api call error accured.
[2024-1-10 14:49:32] [MLUOP] [Error]:"CNNL_STATUS_BAD_PARAM in cnnlSetTransposeDescriptor(NULL, known_dim, known_permute) at /projs/platform/liuduanhui/mluops-dev/mlu-ops/kernels/three_nn_forward/three_nn_forward.cpp line: 54"
> [Fix](mlu-ops): add file and line info to mluOpCnnlCheck func.

- mlu_op.h
fix the comment bug of mlu_op.h
mlu_op.h
- diff1
- diff2
- diff3
- Job types
Test Point-1: `When a new operator is submitted, the test points are given and the test results are stated`. Acceptance …
> [Fix](mlu-ops):fix mlu_op.h comment bug

- kernels/roiaware_pool3d/roiaware_pool3d.cpp
- mlu_op.h
- test/mlu_op_gtest/pb_gtest/src/zoo/roiaware_pool3d_backward/roiaware_pool3d_backward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/roiaware_pool3d_forward/roiaware_pool3d_forward.cpp
增加符合仓库api规范的接口，标注废弃旧接口。同时修改api 调用方式。
modified:   kernels/roiaware_pool3d/roiaware_pool3d.cpp
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/roiaware_pool3d_backward/roiaware_pool3d_backward.cpp
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/roiaware_pool3d_forward/roiaware_pool3d_forward.cpp
- diff1
- diff2
- diff3
- …
> [Feature](mluOpRoiAwarePool3dForward): add roi_aware_pool3d correct api format

- README.md
- build.property
- independent_build.sh
- version_pre_check.py
1.proto 3.9.0版本可以正常编译，但之前限制最高版本为3.8.0
2.版本预检查不通过，应该报warning
1.proto 的限制修改为最低版本为3.6.0
2.“exit强制退出”改成报warning
> [feature](mlu-ops): fix version_pre_chek

- mlu_op.h
Announce mluOpRoiawarePool3dForward, mluOpRoiawarePool3dBackward and mluOpGetRoiAwarePool3dForwardWorkspaceSize to deprecated.
Documentation modify. No test.
> [Docs](mluOpRoiawarePool3dForward): Announce api deprecated.

- test/mlu_op_gtest/pb_gtest/src/gtest/test_env.cpp
getComputeMode 读取文件失败
读写模式可能失败，而getComputeMode 只需要读权限，修改读文件模式.
> [Fix](mlu-ops): Fix getComputeMode

- kernels/sync_batchnorm_backward_reduce/sync_batchnorm_backward_reduce.cpp
- mlu_op.h
- test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_backward_reduce/sync_batchnorm_backward_reduce.cpp
算子api格式错误，新开api并废弃旧的。
modified:   kernels/sync_batchnorm_backward_reduce/sync_batchnorm_backward_reduce.cpp
- diff1
- diff2
- diff3
- Job types
[^      OK ] /workspace/volume/mluops-develop/SOFT_TRAIN/release_test/sync_batchnorm_backward_reduce/syn …
> [Feature](mluOpSyncBatchNormBackwardReduce): Add new API and deprecate old ones

- installer/independent/debian/control
Fix control set for ubuntu22.04 package.
installer/independent/debian/control
do package successfully.
> [Fix](mlu-ops): Fix control set for ubuntu22.04 package.

- mlu_op.h
fix group spell error in mluop.h.
mluop.h
- diff1
- diff2
- diff3
- Job types
Test Point-1: `When a new operator is submitted, the test points are given and the test results are stated`. Acceptance …
> [Fix](mluOpMaskedCol2imForward):fix group spell error in mluop.h.

- .github/workflows/daily.yaml
- .github/workflows/mluops_all_system_ci.yaml
- .github/workflows/mluops_ci.yaml
- README.md
- build.property
- docs/api_guide/update.rst
- docs/release_notes/mlu_ops.rst
- docs/user_guide/2_update_history/index.rst
- docs/user_guide/9_operators/index.rst
- installer/centos7.5/SPECS/mluops-independent.spec
- mlu_op.h
Update docs since MLU-OPS v1.0.0 is going to be released.
modified:   .github/workflows/daily.yaml
modified:   .github/workflows/mluops_all_system_ci.yaml
modified:   .github/workflows/mluops_ci.yaml
modified:   docs/api_guide/update.rst
modified:   docs/release_notes/mlu_ops.rst
modified:   docs/user_guide/2_update_history/index.rst
modified:   docs/user_guide/9_operators/index.rst
No test.
> [Docs](mlu-ops): Update docs for v1.0.0

- kernels/prior_box/prior_box.cpp
fix gencase bug..
kernels/prior_box/prior_box.cpp.
- diff1
- diff2
- diff3
- Job types
Test Point-1: `When a …
> [Fix](mluOpPriorBox):fix gencase bug.

- core/mlu_op_internal_api.h
- core/mlu_op_trace.cpp
> [Feature](mlu-ops): Remove internal_api

- kernels/utils/common.h
> [Fix](mluOpExecFFT):Fix fft bug.

- docs/design_docs/masked_col2im_forward/masked_col2im_forward.md
- docs/design_docs/psroipool_backward/psroipool_backward.md
- test/mlu_op_gtest/pb_gtest/gtest_config/test_list
> [Fix](mlu-ops): fix mlu_only op_list

- docs/design_docs/yolo_box/yolo_box.md
- test/mlu_op_gtest/pb_gtest/gtest_config/test_list
yolo_box受真值影响
test_list 增加 yolo_box
> [Docs](yolo_box): test_list add yolo_box

- test/mlu_op_gtest/pb_gtest/src/zoo/active_rotated_filter_forward/active_rotated_filter_forward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.h
- test/mlu_op_gtest/pb_gtest/src/zoo/masked_col2im_forward/masked_col2im_forward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/moe_dispatch_backward_gate/moe_dispatch_backward_gate.h
- test/mlu_op_gtest/pb_gtest/src/zoo/poly_nms/poly_nms.h
- test/mlu_op_gtest/pb_gtest/src/zoo/roiaware_pool3d_forward/roiaware_pool3d_forward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/roipoint_pool3d/roipoint_pool3d.h
- test/mlu_op_gtest/pb_gtest/src/zoo/three_nn_forward/three_nn_forward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/voxelization/voxelization.h
fix workspacefree() bug.
test/mlu_op_gtest/pb_gtest/src/zoo/active_rotated_filter_forward/active_rotated_filter_forward.h
test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.h
test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.h
test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.h
test/mlu_op_gtest/pb_gtest/src/zoo/masked_col2im_forward/masked_col2im_forward.h
test/mlu_op_gtest/pb_gtest/src/zoo/moe_dispatch_backward_gate/moe_dispatch_backward_gate.h
test/mlu_op_gtest/pb_gtest/src/zoo/poly_nms/poly_nms.h
test/mlu_op_gtest/pb_gtest/src/zoo/roiaware_pool3d_forward/roiaware_pool3d_forward.h …
> [Fix](mlu-ops): fix workspacefree() bug.

- kernels/fft/fft_optm_device/fft_cooley-tukey_ux_device.mlu
> [Fix](mluOpExecFFT): Fix fft doc bug.

- kernels/points_in_boxes/points_in_boxes_block_kernel.mlu
fix precision bug of points_in_boxes
kernels/points_in_boxes/points_in_boxes_block_kernel.mlu
- diff1
- diff2
- diff3
- Job types
yuexiaofan@bjys1083:/projs/cnnl/yuexiaofan/mlu-ops-yxf/build/test$ ./mluop_gtest …
> [Fix](mluOpPointsInBoxes):fix precision bug of points_in_boxes

- version_pre_check.py
…8.10
python 将 废弃 distutils 模块。python3.8.10中已不支持。
1. 使用 try 来引入 version 库，如果没有对应模块，就检查失败，弹出 warning 警告。
> [Fix](mluops): not found distutils in python3.8.4

- kernels/sparse_conv/indice_convolution_forward/indice_convolution_forward.cpp
添加large tensor 防呆，与indice_convolution_backward_filter、indice_convolution_backward_data算子支持的规模匹配。
kernels/sparse_conv/indice_convolution_forward/indice_convolution_forward.cpp
- diff1
- diff2
- diff3
- Job types
测试流水通过: …
> [Feature](indice_convolution_forward): add fool-check for tensor size

- kernels/sparse_conv/indice_convolution_forward/indice_convolution_forward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_forward/indice_convolution_forward.cpp
gen_case逻辑中，多次调用MLUOP_GEN_CASE_ON_NEW时，只有第一次调用会使能。去掉GEN_CASE_END的条件判断。
gtest cpucompute逻辑支持LAYOUT_ARRAY的filter。
kernels/sparse_conv/indice_convolution_forward/indice_convolution_forward.cpp
test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_forward/indice_convolution_forward.cpp
测试流水通过：http://jenkins.svc.cambricon.com/dist/job/MLUOPS/job/MLU_ALL_PLATFORMS/job/mluops_build_test_adaptable_mlu/379/
运行多个测例正常生成gen_case
- diff1
- diff2
- diff3
- …
> [Fix](indice_convolution_forward): fix gen_case and gtest error

- docs/design_docs/active_rotated_filter_forward/active_rotated_filter_forward.md
- kernels/active_rotated_filter/active_rotated_filter.cpp
- test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Fix gen case bug.
docs/design_docs/active_rotated_filter_forward/active_rotated_filter_forward.md
kernels/active_rotated_filter/active_rotated_filter.cpp
test/mlu_op_gtest/pb_gtest/gtest_config/test_list
- diff1
- diff2
- diff3
- …
> [Fix](mluOpActiveRotatedFilterForward): Fix gencase bug.

- CMakeLists.txt
- independent_build.sh
- samples/mlu-ops/abs_sample/CMakeLists.txt
- samples/mlu-ops/abs_sample/build.sh
- samples/mlu-ops/env.sh
Generate mluops static lib
CMakeLists.txt
samples/mlu-ops/abs_sample/CMakeLists.txt
samples/mlu-ops/abs_sample/build.sh
samples/mlu-ops/env.sh
- diff1
- diff2
- diff3
- Supported …
> [Feature](mlu-ops): Support mluops static library compiling.

- kernels/adam_w/adam_w.cpp
> [Feature](mluOpAdamW): add param check for adam_w

- independent_build.sh
Change ret code in independent_build.sh
- diff1
- diff2
- diff3
- Job types
Test Point-1: `When a new operator is submitted, the test points are given and the test results are …
> [Fix](mlu-ops):fix independent_build.sh return code.

- samples/mlu-ops/abs_sample/CMakeLists.txt
- samples/mlu-ops/fault_sample/CMakeLists.txt
- samples/mlu-ops/poly_nms_sample/CMakeLists.txt
…mpiling samples.
- diff1
- diff2
- diff3
- …
> [Feature](mlu-ops): remove the compiling to target 200 series when mpiling samples

- samples/mlu-ops/abs_sample/CMakeLists.txt
- samples/mlu-ops/fault_sample/CMakeLists.txt
- samples/mlu-ops/poly_nms_sample/CMakeLists.txt
> [Fix](mlu-ops): Fix compiling error of sample on target 200 series branch r1.1.

- independent_build.sh
- installer/centos7.5/SPECS/mluops-independent.spec
> [Fix](mlu-ops): Fix the softlink relation in rpm package r1.1.

- kernels/adam_w/adam_w.cpp
- kernels/adam_w/adam_w.h
- kernels/adam_w/adam_w_union1.mlu
> [Fix](mluOpAdamW): fix invoke kernel error

- tools/perf_analyse/parser.py
When we run the perf tool to compare multiple operators, the comparison can fail. The reason is that 2 dataframes need to be merged according to their common keys called "protoName". ProtoNames are the names of calculators' testcases, which means there are a lot of repetitive ones like case0 or case_0. But as a key, protoName should be unique in each dataframe. Repetitive names means that merging 2 dataframes can result in incorrect results.
I have changed the name of the protoname in function preprocess in file parser.py to the full path of the test case of each calculator so that there are no repeated protoNames.
This is the png generated by the python file for all the calculators, which means the now the bug is …
> [Fix](mlu-ops): Fix an error of perf analyses of the whole bench

- docs/design_docs/generate_proposals_v2/generate_proposals_v2.md
- kernels/generate_proposals_v2/generate_proposals_v2.cpp
- kernels/generate_proposals_v2/generate_proposals_v2.h
- kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
- kernels/generate_proposals_v2/generate_proposals_v2_union1_590.mlu
- kernels/generate_proposals_v2/generate_proposals_v2_union_default.mlu
- mlu_op.h
1. Motivation
check nan/inf state and reconstruct && perf box decode
2. Modification
modified: kernels/generate_proposals_v2/generate_proposals_v2.cpp
modified: kernels/generate_proposals_v2/generate_proposals_v2.h
new file: kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
new file: kernels/generate_proposals_v2/generate_proposals_v2_union1_590.mlu
new file: kernels/generate_proposals_v2/generate_proposals_v2_union_default.mlu
For static threshold standard details, see: [MLU-OPS™ Accuracy Acceptance …
> [Feature](mluOpGenerateProposalsV2): check nan/inf state and reconstruct && perf box decode

- tools/perf_analyse/parser.py
Fix the name of prototype so that there is no duplicated names.
When we run the perf tool to compare multiple operators, the comparison can fail. The reason is that 2 dataframes need to be merged according to their common keys called "protoName". ProtoNames are the names of calculators' testcases, which means there are a lot of repetitive ones like case0 or case_0. But as a key, protoName should be unique in each dataframe. Repetitive names means that merging 2 dataframes can result in incorrect results.
I have changed the name of the protoname in function preprocess in file parser.py to the full path of the test case of each calculator so that there are no repeated protoNames.
This is the png generated by the …
> [Fix](mlu-ops): Fix an error of perf analyser

- kernels/carafe/carafe_block.mlu
- kernels/deform_roi_pool/deform_roi_pool_union1.mlu
- kernels/psroipool/psroipool_block.mlu
- kernels/roi_align_rotated/roi_align_rotated_block.mlu
- kernels/roi_crop/roi_crop_block.mlu
- kernels/rotated_feature_align/rotated_feature_align_block.mlu
Replace __bang_atomic_add with __bang_atomic_reduce_add for better performance.
modified:   kernels/carafe/carafe_block.mlu
modified:   kernels/deform_roi_pool/deform_roi_pool_union1.mlu
modified:   kernels/psroipool/psroipool_block.mlu
modified:   kernels/roi_align_rotated/roi_align_rotated_block.mlu
modified:   kernels/roi_crop/roi_crop_block.mlu
modified:   kernels/rotated_feature_align/rotated_feature_align_block.mlu
These two apis has no functional difference. Use CI test as test report.
> [Feature](mlu-ops): Replace atomic_add with atomic_reduce_add

- docs/MLU-OPS-Compile-Develop-And-Test.md
Fix typo in markdown.
modified:   docs/MLU-OPS-Compile-Develop-And-Test.md
> [Docs](mlu-ops): Fix typo in markdown.

- version_pre_check.py
特殊版本号无法比较，会导致 version_check 错误，影响编译.
version comp 时，抓取所有异常
> [Fix](mlu-ops): catch version_compare error

- test/mlu_op_gtest/pb_gtest/src/zoo/deform_roi_pool_backward/deform_roi_pool_backward.cpp
…- c * b not equal to (a-c)*b
a * b - c * b 在特殊情况下不等于 (a - c) *b
不做简化，恢复原来代码
> [Fix](mluOpDeformRoiPoolBackward): fix cpuCompute

- test/mlu_op_gtest/pb_gtest/src/zoo/sync_batchnorm_gather_stats_with_counts/sync_batchnorm_gather_stats_with_counts.cpp
Fixed a bug that gtest did not distinguish whether the input which is called "input" was present.
Added the distinction of whether the input which is called "input" was present.
> [Feature](mluOpSyncBatchNormGatherStatsWithCounts):Update sync_batchnorm_gather_stats_with_counts gtest

- core/util.cpp
- kernels/utils/cnnl_helper.cpp
- tools/pre-commit
removing error throwing in mluops compiled library.
kernels/utils/cnnl_helper.cpp
- diff1
- diff2
- diff3
- Job types
If you have checked the following items, please tick the …
> [Feature](mlu-ops): removing error throwing in mluops library.

- kernels/generate_proposals_v2/generate_proposals_v2.cpp
- kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
- kernels/generate_proposals_v2/generate_proposals_v2_union1_500.mlu
- test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.cpp
support vars/box_deltas/im_shape/anchors tensor nan/inf except score tensor.
modified:   kernels/generate_proposals_v2/generate_proposals_v2.cpp
modified:   kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
modified:   kernels/generate_proposals_v2/generate_proposals_v2_union1_500.mlu
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.cpp
> [Fix](mluOpGenerateProposalsV2): support nan/inf except score tensor.

- independent_build.sh
Support AnolisOS compilation.
modified:   independent_build.sh
Compiling success in AnolisOS.
> [Featrue](mlu-ops): Add support for Anolis

- core/context.cpp
> [Feature](mlu-ops): sup 365-d2

- core/logging.h
- core/tensor.cpp
- core/tensor.h
- core/type.cpp
- core/type.h
- kernels/ball_query/ball_query.cpp
- kernels/sparse_conv/get_indice_pairs/normal_get_indice_pairs.cpp
Provide 10%+ performance boost
logging.h增加静态分支预测,优化deque和desc的逻辑
modified: core/logging.h
modified: core/tensor.cpp
modified: core/tensor.h
modified: core/type.cpp
modified: core/type.h
modified: kernels/ball_query/ball_query.cpp
modified: kernels/sparse_conv/get_indice_pairs/normal_get_indice_pairs.cpp
- diff1
- diff2
- diff3
- float32, …
> [Feature](mlu-ops): optimization for descritpor

- kernels/fft/c2c_fft/c2c_fft_host.cpp
- kernels/fft/common/fft_basic_ops.cpp
- kernels/fft/common/fft_basic_ops.h
- kernels/fft/fft.cpp
- kernels/fft/fft_optm_device/fft_two-level_network_c2c_device.mlu
- kernels/fft/irfft/irfft_host.cpp
- kernels/fft/rfft/rfft_host.cpp
- kernels/utils/cnnl_helper.cpp
- kernels/utils/cnnl_helper.h
- mlu_op.h
- test/mlu_op_gtest/api_gtest/include/api_test_tools.h
- test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_ExecFFT.cpp
- test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_MakeFFTPlanMany.cpp
- test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_general.cpp
> [Feature](mluOpExecFFT): fix accuracy and performance bug

- kernels/fft/irfft/irfft_host.cpp
> [Fix](mluOpExecFFT): fix irfft1d bug

- kernel_depends.toml
- kernels/lgamma/lgamma.cpp
- kernels/lgamma/lgamma.h
- kernels/lgamma/lgamma_block.mlu
- mlu_op.h
- test/mlu_op_gtest/pb_gtest/src/zoo/lgamma/lgamma.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/lgamma/lgamma.h
add new operator lgamma
add implementation of lgamma
not yet
- diff1
- diff2
- diff3
- float32, threshold = 3e-3
- float16, threshold = 3e-3
- Job types
```bash
[       OK ] lgamma/TestSuite.mluOp/70 (62 ms)
[----------] 71 tests from lgamma/TestSuite (3641 ms total)
[ SUMMARY  ] Total 71 cases of 1 op(s).
ALL PASSED.
[==========] 71 test cases from 1 test suite …
```
> [Feature](mluOpLgamma) add new operator lgamma

- kernels/fft/c2c_fft/c2c_fft_host.cpp
- kernels/fft/fft.cpp
- kernels/fft/irfft/irfft_host.cpp
- kernels/fft/rfft/rfft_host.cpp
> [Fix](mluOpSetFFTReserveArea): fix fft bug.

- installer/centos7.5/SPECS/mluops-independent.spec
Fix bogus date error for centos7.
> [Fix](mlu-ops): Fix bogus date error for centos7

- core/tensor.cpp
> [Fix](mlu-ops) fix mem leak in core-mode

- docs/design_docs/roiaware_pool3d_forward/roiaware_pool3d_forward.md
- kernels/binary_op/binary_op_3pipeline.h
- kernels/border_align/border_align_backward/border_align_backward_union1.mlu
- kernels/box_iou_rotated/box_iou_rotated_aligned.h
- kernels/box_iou_rotated/box_iou_rotated_nonaligned.h
- kernels/box_iou_rotated/box_iou_rotated_utils.h
- kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
- kernels/focal_loss_sigmoid/focal_loss_sigmoid_forward_union1.mlu
- kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
- kernels/lgamma/lgamma_block.mlu
- kernels/log/log_union1.mlu
- kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
- kernels/nms_rotated/nms_rotated_union1.mlu
- kernels/nms_rotated/nms_utils.h
- kernels/three_nn_forward/three_nn_forward_union1.mlu
- kernels/unary_op/complex_unary_op_3pipeline.h
- kernels/unary_op/unary_op_3pipeline.h
- kernels/unary_op/unary_op_4pipeline.h
- kernels/unary_op/unary_op_no_pipeline.h
- kernels/utils/common.h
- kernels/voxelization/voxelization_kernel.mlu
- kernels/yolo_box/yolo_box_block.mlu
> [Feature](mlu-ops): Update to toolkit4+

- kernels/lgamma/lgamma.cpp
- kernels/lgamma/lgamma.h
- kernels/lgamma/lgamma_block.mlu
- test/mlu_op_gtest/pb_gtest/src/zoo/lgamma/test_case/case_0.prototxt
> [Fix](mluOpLgamma): fix lgamma for large tensor.

- kernels/fft/common/fft_basic_ops.cpp
> [Fix](mluOpExecFFT): fix fft bug

- kernels/device_check.h
- kernels/kernel.h
- test/mlu_op_gtest/pb_gtest/src/zoo/adam_w/adam_w.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/box_iou_rotated.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/carafe_forward/carafe_forward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_weight/dcn_backward_weight.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_forward/dcn_forward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/div/div.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/focal_loss_sigmoid_backward/focal_loss_sigmoid_backward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_backward_data/indice_convolution_backward_data.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/log/log.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/nms/nms.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/nms_rotated/nms_rotated.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/sqrt/sqrt.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/sqrt_backward/sqrt_backward.cpp
- tools/pre-commit
assert 只在 debug 模式下使能，gtest端将assert用GTEST_CHECK替代，host端不应该使用assert而是做paramcheck，device端检查真值使用MLU_KERNEL_ASSERT
MLU_KERNEL_ASSERT 宏更新
gtest端 assert 替换
pre-commit 检查更新，不会再防住 static_assert 等
> [Feature](mluops): Normalize assert

- kernels/adam_w/adam_w.cpp
- kernels/adam_w/adam_w_union1.mlu
> [Fix](mluOpAdamW): fix debug mode error and add arch check for bf16

- test/mlu_op_gtest/pb_gtest/src/executor.cpp
- test/mlu_op_gtest/pb_gtest/src/executor_float_old.cpp
- test/mlu_op_gtest/pb_gtest/src/parser.cpp
- test/mlu_op_gtest/pb_gtest/src/stride.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/indice_convolution_forward/indice_convolution_forward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/moe_dispatch_backward_data/moe_dispatch_backward_data.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/moe_dispatch_forward/moe_dispatch_forward.cpp
> [Feature](mlu-ops): change getSizeOfDataType to mluOpGetSizeOfDataType.

- kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_forward.mlu
> [Fix](mluOpMsDeformAttnForward): fix gen_case.

- core/tensor.cpp
> [Fix](mluOPTensor) Fix double free memory error in tensor.cpp

- kernels/nms_rotated/nms_rotated_union1.mlu
- kernels/nms_rotated/nms_utils.h
fix warning
kernels/nms_rotated/nms_rotated_union1.mlu
kernels/nms_rotated/nms_utils.h
- diff1
- diff2
- diff3
- Job types
If you have checked the following items, please tick the …
> [Fix](mluOpNmsRotated): fix warning.

- kernels/mutual_information/mutual_information_backward/mutual_information_backward_3pipeline_block.mlu
- kernels/mutual_information/mutual_information_backward/mutual_information_backward_default_block.mlu
- kernels/mutual_information/mutual_information_forward/mutual_information_forward_default_block.mlu
Add sync to fix race check in mutual information op.
Add sync to fix race check in mutual information op.
- diff1
- diff2
- diff3
- Job types
Test Point-1: `When a new operator is submitted, the …
> [Fix](mluOpMutualInformationBackward/Forward): fix race check error

- kernels/logspace/logspace_block.mlu
fix float2int bug using __cn_vector_cast_f32_to_s32().
kernels/logspace/logspace_block.mlu
> [Fix](mluOpLogspace): Fix logspace bug.

- docs/design_docs/roi_align_rotated/roi_align_rotated.md
- docs/design_docs/roi_align_rotated/roi_align_rotated_forward_vector.md
- kernels/roi_align_rotated/roi_align_rotated.cpp
- kernels/roi_align_rotated/roi_align_rotated.h
- kernels/roi_align_rotated/roi_align_rotated_block.mlu
- kernels/roi_align_rotated/roi_align_rotated_forward_vector.mlu
- kernels/utils/common.h
> [Feature](mluOpRoiAlignRotatedForward): Refactor roi align rotated forward

- kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
1. Motivation
2. Modification
kernels/focal_loss_sigmoid/focal_loss_sigmoid_backward_union1.mlu
3. Test Report
修改前：
[ 50%] Building CNCC object CMakeFiles/mluops.dir/kernels/focal_loss_sigmoid/mluops_generated_focal_loss_sigmoid_backward_union1.mlu.o
[ 54%] Built target pb2prototxt
[ 56%] Built target prototxt2pb
[ 92%] Built target mluop_pb_gtest_obj
warning: unknown address space, please use addrspace-specified load/store functions.
for example: __load_nram.
warning: unknown address space, please use addrspace-specified load/store functions.
for example: __load_nram.
Consolidate compiler generated dependencies of target mluops
[ 93%] Linking CXX shared library lib/libmluops.so
[ 97%] Built target …
> Fix(mluOpFocalLossSigmoidBackward): fix unknown address space warning

- kernels/fft/common/fft_basic_ops.cpp
> [Fix](mluOpMakeFFTPlanMany): Fix memory leaks bug.

- docs/design_docs/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.md
- docs/design_docs/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.md
- kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.cpp
- kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.h
- kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward_union1.mlu
> [Feature](mluOpDynamicPointToVoxelBackward): to be better performance

- kernels/rotated_feature_align/rotated_feature_align_block.mlu
fix the compile warning of "llvm.memset"
kernels/rotated_feature_align/rotated_feature_align_block.mlu
use CI as simple test
> [Fix](mluOpRotatedFeatureAlignForward): Fix memset warning

- test/mlu_op_gtest/pb_gtest/src/parser.cpp
- test/mlu_op_gtest/tools/pb2prototxt.cpp
> [Fix](mlu-ops): solve protobuf version compatibility.

- test/mlu_op_gtest/pb_gtest/src/parser.cpp
- test/mlu_op_gtest/tools/pb2prototxt.cpp
> [Fix](mlu-ops): solve protobuf version compatibility r.14.

- kernels/box_iou_rotated/box_iou_rotated_utils.h
- kernels/generate_proposals_v2/generate_proposals_v2_union1_500.mlu
- kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
- kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
- kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_utils.h
- kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
- kernels/roi_align_rotated/roi_align_rotated_forward_vector.mlu
- kernels/utils/scatter_gather.h
- kernels/voxel_pooling_forward/voxel_pooling_forward_union1.mlu
- kernels/voxelization/voxelization_kernel.mlu
> [Feature](mlu-ops): adapt scatter,gather

- core/context.cpp
- core/context.h
- independent_build.sh
> [Feature](mlu-ops): Support mtp_613

- docs/design_docs/roi_align_rotated/roi_align_rotated_forward_vector.md
- kernels/roi_align_rotated/roi_align_rotated_forward_vector.mlu
存在潜在的内存竞争。构造二维坐标序列时没有sync，它依赖的增序队列构造和后续计算指令可能有竞争。
> [Fix](mluOpRoiAlignRotatedForward): fix race_mem error

- kernels/fft/c2c_fft/c2c_fft_host.cpp
- kernels/fft/irfft/irfft_host.cpp
- kernels/fft/rfft/rfft_host.cpp
In 2d, n0==1 || n1==1 is actually a 1d FFT calculation. This part of the case call 2d calculation result error problem is now modified.
- diff1
- diff2
- diff3
- …
> [Fix](mluOpExecFFT): fix bug about 2d n0==1 || n1==1.

- kernels/nms_rotated/nms_rotated_union1.mlu
fix race_checkerror
1. store.gpr is async operation, sync should be insert before load data from the mem has been writed.
2. MLU Core write the same address with same data should be revised with only one core to write data.
kernels/nms_rotated/nms_rotated_union1.mlu
functional test and perf test pipeline passed.
> [Fix](mluOpNmsRotated): fix race_check error.

- kernels/fft/c2c_fft/c2c_fft_host.cpp
- kernels/fft/common/fft_basic_ops.cpp
- kernels/fft/fft.cpp
- kernels/fft/irfft/irfft_host.cpp
- kernels/fft/rfft/rfft_host.cpp
> [Fix](mluOpExecFFT): fix memory leak and wrong using of check marco.

- kernels/fft/common/fft_basic_ops.cpp
- kernels/fft/common/fft_basic_ops.h
- kernels/fft/fft.cpp
Add perf border to cooley_tuky and stockham kernel
Make dft to support 4098 length.
modified:   kernels/fft/common/fft_basic_ops.cpp
modified:   kernels/fft/common/fft_basic_ops.h
modified:   kernels/fft/fft.cpp
modified:   kernels/fft/fft.h
- diff1
- diff2
- diff3
- dynamic …
> [Feature](mluOpExecFFT): add perf border for cooleytuky and stockham kernel.

- kernels/fft/c2c_fft/c2c_fft_host.cpp
- kernels/fft/fft.cpp
- kernels/fft/fft.h
- kernels/fft/irfft/irfft_host.cpp
- kernels/fft/rfft/rfft_host.cpp
- test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_general.cpp
Improve 1d fft perf when length <= 4098 on 500.
kernels/fft/fft.cpp
kernels/fft/fft.h
- diff1
- diff2
- diff3
- Job types
If you have checked the following items, please tick the …
> [Feature](mluOpExecFFT): improve perf for 1d fft when case is 4098

- kernels/nms_rotated/nms_utils.h
> [Fix](mluOpNmsRotated): restore the perf of nms rotated by not use mpu

- test/mlu_op_gtest/pb_gtest/gtest_config/internal_test_list
- test/mlu_op_gtest/pb_gtest/src/parser.cpp
> [Feature](mlu-ops): 添加真值相关算子的test_list.

- kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward.cpp
- kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_small_channels_union1.mlu
mask 是做判断逻辑，直接用 mask 做乘法，会出现 0 * nan/inf 的错误.
删除mask做向量乘的实现
> [Fix](mluOpMsDeformAttnBackward): cant use mask mul vector

- kernels/adam_w/adam_w.cpp
Fix the gen_case bug of adam_w, specifically, the adam_w operator folder naming and parameter name modification.
Modify the parameter name when genrating the prototxt.
- diff1
- diff2
- diff3
- Job types
```bash …
```
> [Fix](mlu-ops): fix the parameter name error of the adam_w gen_case.

- kernels/carafe/carafe.cpp
- kernels/div/div.cpp
- kernels/div/div.h
- kernels/div/div_union1.mlu
- kernels/fft/fft.h
- kernels/log/log.h
- kernels/log/log_union1.mlu
- kernels/sqrt/sqrt_union1.mlu
- kernels/tensor_stride_process/tensor_stride_in_block.mlu
- kernels/tensor_stride_process/tensor_stride_out_block.mlu
- kernels/tensor_stride_process/tensor_stride_process_host.cpp
- kernels/tensor_stride_process/tensor_stride_process_host.h
- kernels/tensor_stride_process/tensor_stride_process_mlu.h
- kernels/tensor_stride_process/tensor_stride_process_mlu.mlu
- kernels/unary_op/unary_op_stride_3pipeline.h
提高div，log，sqrt算子的覆盖率，对其中冗余代码进行删除和修改，其中具体如下：
- div算子相关代码停止维护
- log算子中的五级流水在log.cpp未被调用，这导致该算子覆盖率过低
- sqrt算子中出现指代不名的数字
删除div算子中有关停止维护的三级流水的冗余代码。
删除log算子相关的五级流水代码定义与实现。
更改sqrt算子中指代不明的数字。
> [Fix](mlu-ops):remove redundant code in the div, log, sqrt operators.

- kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
Fix NaN error for large channel input.
modified:   kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
Test adaptable pass.
> [Feature](ms_deform_attn_forward): Fix error of nan for larger channels.

- kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward_union1.mlu
修复dynamic_point_to_voxel，正确索引应始终只由 voxel id 和 feature 块内偏移决定
modified:   kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward_union1.mlu
Use CI test result as report.
> fix(dynamic_point_to_voxel): fix incorrect voxel_feats_offset

- kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward_union1.mlu
lcsFunc中，在处理余数部分时，逻辑把 load(rem_num) 和前一块的 compute(deal_h) 落到了同一个缓冲区；
导致 compute 还没消费完，就被新的 load 覆盖了，出现数据踩踏。
modified:   kernels/dynamic_point_to_voxel/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward_union1.mlu
Use CI test result as report.
> fix(dynamic_point_to_voxel): fix load/compute overlap causing buffer
