Cambricon/mlu-ops

- bangpy-ops/ops/nms/test_nms.py
> fix(nms): Parametrized the test of nms

- bangc-ops/mlu_op.h
fix(bangc-ops): delete unused test mluop api in mlu_op.h
> fix(bangc-ops): delete unused test mluop api in mlu_op.h

- tools/pre-commit
[Feature](bangpy-ops): add pylint check into pre-commit check.
> [Feature](bangpy-ops): add pylint check into pre-commit check.

- bangc-ops/test/mlu_op_gtest/pb_gtest/include/parser.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/parser.cpp
fix large tensor parsed failure issue
> fix(bangc-ops):fix large tensor parsed failure issue

- .github/workflows/ci.yaml
- .github/workflows/coverage_test.yaml
- bangc-ops/kernels/div/div_block.mlu
- bangc-ops/kernels/log/log_block.mlu
- bangc-ops/kernels/psroipool_forward/psroipool_forward_block.mlu
- bangc-ops/kernels/roi_crop/roi_crop_block.mlu
- bangc-ops/kernels/sqrt/sqrt_block.mlu
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/test_env.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/include/executor.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/executor.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/gtest/mlu_op_gtest.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/gtest/test_env.cpp
- build.sh
- docker/ubuntu16.04-x86_64/Dockerfile
- docs/bangc-docs/design_docs/roi_crop/roi_crop_design_docs.md
- test.sh
[Fix](bangc-ops):update cnrt api and cntoolkit version.
> [Fix](bangc-ops):update cnrt api and cntoolkit version.

- env.sh
feat(bangc-ops): support user defined NEUWARE_HOME.
> feat(bangc-ops): support user defined NEUWARE_HOME.

- README.md
- bangc-ops/core/mlu_op_core.h
Co-authored-by: wangyuan <wangyuan@cambricon.com>
> [Docs](bangc-ops) modify version-msg (#124)

- env.sh
- tools/commit-msg
- tools/commitlint.py
add commit message check for mlu-ops.
> [Feature](mlu-ops):add commit message check for mlu-ops.

- bangc-ops/build.sh
[Feature](bangc-ops):add environment check for centos when build bangc-ops.
> [Feature](bangc-ops):add environment check for centos when build bangc-ops.

- build.property
- independent_build.sh
- json_parser.py
[Feature](bangc-ops): add shell script for deliver deb package.
> [Feature](bangc-ops): add shell script for deliver deb package.

- docs/pr.md
Revise some description in pr.md.
> [Docs]: Revise some description in pr.md.

- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
[Fix](bangc-ops): fix centos spec files.
> [Fix](bangc-ops): fix centos spec files.

- .github/pull_request_template.md
Thanks for your contribution and we appreciate it a lot. Please state your motivation and modification for this pull_request here.
Please describe the motivation of this PR and the goal you want to achieve through this PR.
Please briefly describe what modification is made in this PR ，and indicate where to modify it.
> [fix]: fix mlu_ops docs

- bangc-ops/core/tensor.cpp
- bangc-ops/core/tensor.h
- bangc-ops/mlu_op.h
[Fix](bangc-ops):fix large tensor bug.
> [Fix](bangc-ops):fix large tensor bug.

- bangc-ops/CMakeLists.txt
- bangc-ops/core/tensor.cpp
- bangc-ops/core/tensor.h
> [Fix](bangc-ops):delete global var name

- bangc-ops/CMakeLists.txt
- bangc-ops/core/tensor.cpp
- bangc-ops/core/tensor.h
Modify global variable names to resolve conflicting symbols with other libraries
Add the library name prefix to the global variable name in the "mlu_ops/bangc_ops/core/tensor.cpp" file
|        3       | …
> [Fix](bangc-ops):fix global var name

- .github/workflows/ci.yaml
- test.sh
Add more case testing function for bangc-ops ci evalution
test.sh
.github/workflow/ci.yaml
> [Feature](mlu-ops): add more case testing function for bangc-ops ci evalution

- independent_build.sh
Revise independent shell for debian package
> [Fix](bangc-ops): revise independent shell for debian.

- .github/workflows/bangcops_release_test.yaml
Add release ci test for bangc-ops
.github/workflow/bangc_release_test.yaml
> [Feature](bangc-ops): add release test ci configuration for bangc-ops.

- bangc-ops/kernels/prior_box/prior_box.cpp
> [Fix](bangc-ops):Prior box fix max_size defensive.

- docs/bangc-docs/build.sh
> [Docs](bangc-ops): Added the doc compiling

- bangpy-ops/ops/add/add.py
- bangpy-ops/ops/adjust_hue/adjust_hue.py
- bangpy-ops/ops/nonzero/nonzero.py
- bangpy-ops/ops/nonzero/nonzero_count.py
修改算子中的syntax error
1. 修改了add算子的注释
2. 修改了adjust_hue和nonzero算子里面的syntax error
> fix(bangpy-ops): fix the syntax of bangpy ops.

- .github/workflows/bangcops_release_test.yaml
- bangc-ops/test/version_check/version_check.cpp
- version_check.sh
[Feature](bangc-ops):add release test ci mluops verison check
> [Feature](bangc-ops):add release test ci mluops verison check.

- independent_build.sh
1. motivation
fix test tar config
2.modification
indepentdent_build.sh
> [Fix](bangc-ops): fix test tar configuration.

- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
- installer/independent/debian/changelog
- installer/ubuntu16.04/debian/changelog
revise release changelog files
modified:   installer/independent/debian/changelog
modified:   installer/ubuntu16.04/debian/changelog
> [Fix](mlu-ops): revise release changelogs.

- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
fix centos package configure files.
> [Fix](bangc-ops): fix centos package configure files.

- independent_build.sh
- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
fix centos package spec file.
modified:   independent_build.sh
> [Fix](bangc-ops): fix centos package spec file.

- docs/bangc-docs/api_guide/conf.py
> [Docs](bangc-ops): Improved the API doc

- docs/bangc-docs/api_guide/makelatexpdf.sh
- docs/bangc-docs/build.sh
- docs/bangc-docs/release_notes/conf.json
- docs/build.sh
[Feature](bangc-ops):add bangc ops doc build shell.
> [Feature](bangc-ops):add bangc ops doc build shell.

- bangc-ops/mlu_op.h
[Feature](bangc-ops): Fix doc some details.
> [Feature](bangc-ops): Fix doc some details.

- bangc-ops/core/logging.h
> [Fix](bangc-ops): fix core/logging.h code error

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.cpp
- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.mlu
- bangc-ops/kernels/poly_nms/enums.h
- bangc-ops/kernels/poly_nms/intersect_area.h
- bangc-ops/kernels/poly_nms/poly_nms.h
- bangc-ops/kernels/poly_nms/poly_nms.mlu
- bangc-ops/kernels/poly_nms/poly_nms_block_calc_area.mlu
- bangc-ops/kernels/poly_nms/poly_nms_block_gen_mask.mlu
- bangc-ops/kernels/poly_nms/poly_nms_block_gen_result.mlu
- bangc-ops/kernels/poly_nms/poly_nms_core_set.h
- bangc-ops/kernels/poly_nms/poly_nms_kernel_launch.mlu
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/poly_nms/pnms_impl.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/poly_nms/pnms_impl.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/poly_nms/poly_nms.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/poly_nms/poly_nms.h
- docs/bangc-docs/design_docs/generate_proposals_v2/generate_proposals_v2.md
影响范围/算子：generate_proposals_v2
影响版本/分支：master
1.1 精度验收标准
按照[精度验收标准](https://github.com/Cambricon/mlu-ops/blob/1dd886d78b53f9e3b4783b948b7ba28b422f4851/docs/bangc-docs/design_docs/MLU_OPS%E7%B2%BE%E5%BA%A6%E9%AA%8C%E6%94%B6%E6%A0%87%E5%87%86.md)的要求明确本算子的精度标准
 generate_proposals_v2 是复合类算子。
rpn_rois参数精度设为 diff1 <= 3e-3 && diff2 <=3e-3。
rpn_roi_probs、rpn_rois_num、rpn_rois_batch_size的精度设置为 diff3=0。
1.2 算子方案CHECKLIST
序号 | 需求 | 需求详情
-- | -- | --
1 | 支持硬件 | MLU270MLU290MLU370
2 | job类型 | blockU1U4Ux
3 | DimXYZ | 支持DimXYZ
4 | 可变 | 不支持各个维度可变
5 | layout | ARRAY
6 | 多维 | 不支持多维
7 | 0元素 | 支持0元素
8 | 转数提前 | 否
9 | 片上数据类型 | float
10 | 片外数据类型 | float
11 | 融合 | 否
12 | 规模限制 |  
13 | c不感知对齐 | 否
14 | 代码覆盖率 |  
15 | 内存泄露 | 无
16 | IO计算效率检查 | 是
<h5 class="code-line" id="generate_proposals_v2算子测试报告-1.3算子限制" …
> [fix](bangc-ops): fix  getKthScores bug

- .github/workflows/ci.yaml
add ci check for released branches.
github/workflow/ci.yaml
> [Feature](mlu-ops): add ci check for release branches.

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/executor.cpp
> [Fix](bangc-ops): fix executor code bug

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.cpp
- bangpy-ops/ops/adjust_hue/active_table.py
- bangpy-ops/ops/adjust_hue/adjust_hue.py
- bangpy-ops/ops/adjust_hue/test_adjust_hue.py
- bangpy-ops/ops/nms/nms.py
- bangpy-ops/ops/nms/test_nms.py
- bangpy-ops/ops/nonzero/nonzero.py
- bangpy-ops/ops/nonzero/nonzero_count.py
- bangpy-ops/test/__init__.py
- bangpy-ops/test/execuator.py
- bangpy-ops/test/optest.py
- bangpy-ops/test/parser.py
- bangpy-ops/test/test_op.py
Modify the typos in the copyright.
Modify the typos in the copyright.
> [fix](copyright): fix the typos in copyright

- .github/workflows/ci.yaml
- .github/workflows/daily.yaml
> [Feature](bangc): update ci.yaml

- bangc-ops/mlu_op.h
> [Fix](bangc-ops): update interface note

- samples/bangc-ops/abs_sample/build.sh
- samples/bangc-ops/build.sh
- samples/bangc-ops/fault_sample/build.sh
- samples/bangc-ops/poly_nms_sample/build.sh
Modify the compile script for samples
> [Fix](bangc-ops):Modify the compile script for samples

- docs/bangc-docs/design_docs/ball_query/ball_query.md
删除ball_query中的cnnl字符串
https://github.com/Cambricon/mlu-ops/issues/272
> [docs](bangc-ops):delete cnnl string in ball_query

- bangc-ops/README.md
Update the README file to add the compiler specified operator
Update the README file to add the compiler specified operator
> [Docs](bangc-ops):Update the README file 

- bangc-ops/CMakeLists.txt
- bangc-ops/build.sh
- bangc-ops/test/mlu_op_gtest/CMakeLists.txt
support debug mode and delete --gtest-filter cmd
support debug mode and delete --gtest-filter cmd
|        3       |         Layouts            |  NHWC 、NCHW、ARRAY etc    |
| …
> [Feature](bangc-ops): support debug mode and delete --gtest-filter cmd

- bangpy-ops/test/mlu_op_test_pb2.py
- bangpy-ops/utils/build_and_test_all_operators.py
- bangpy-ops/utils/build_operators.sh
> [FIX](bangpy-ops)update some test ops config

- bangc-ops/README.md
Modify the readme error description
bangc-ops/README.md
> [Fix](bangc-ops): Modify the readme error description

- CPPLINT.cfg
- bangc-ops/mlu_op.h
- tools/check_log_error.py
- tools/pre-commit
update code style check to check mlu_op.h style except linelength.
remove redundant info from check_log_error.py
modified:   CPPLINT.cfg
modified:   tools/check_log_error.py
modified:   tools/pre-commit
> [Fix](bangc-ops): update code style check for mlu_op.h

- bangc-ops/README.md
- bangc-ops/kernel_depends.toml
> [feature](bangc-ops): Improve the single operator compilation function

- bangc-ops/core/context.cpp
- bangc-ops/core/gen_case.cpp
- bangc-ops/core/gen_case.h
- bangc-ops/core/logging.h
- bangc-ops/core/tensor.cpp
- bangc-ops/core/tensor.h
- bangc-ops/core/tool.cpp
- bangc-ops/core/tool.h
- bangc-ops/core/type.h
Improve code under core file
1. mlu-ops/bangc-ops/core
|        3       |         Layouts            |  NHWC 、NCHW、ARRAY etc    |
|        4       |         Whether multi-dimensions …
> [Fix](bangc-ops):synchronize code in core files

- CPPLINT.cfg
- bangc-ops/mlu_op.h
- env.sh
- tools/format2google
- tools/pre-commit
revise format tools and pre-commit tools for better code style.
revise mlu-op.h format. 
modified:   env.sh
modified:   tools/format2google
modified:   tools/pre-commit
> [Fix](bangc-ops): revise pre-commit and format tools and mlu_op.h.

- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
> [Feature](bangc-ops):add op_type in proto.

- bangc-ops/CMakeLists.txt
> [Fix](bangc-ops): fix bangc-ops cmakelist add link dl lib

- bangc-ops/kernels/ball_query/ball_query.h
- bangc-ops/kernels/ball_query/ball_query_union1.mlu
> [Fix](bangc-ops):fix incorrect license spelling.

- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
Modify proto.
Add MLU590 and handle_param in Node.
> add MLU590 and handle_param in proto

- .github/workflows/ci.yaml
update ci server for mlu-ops-0.4.0.
> update ci server for mlu-ops-0.4.0

- .github/workflows/daily.yaml
> Update daily docker image address

- .github/workflows/bangcops_release_test.yaml
- build.property
Update mlu-ops version from v0.3.0 to v0.4.0.
> Update mlu-ops version

- .github/workflows/bangcops_release_test.yaml
> upgrade ci docker image

- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
Update Fill ParamId.
Modify mlu_op_test.proto fill
> [Fix](bangc-ops): update fill param id

- docs/bangc-docs/api_guide/update.rst
- docs/bangc-docs/release_notes/bangc_ops.rst
- docs/bangc-docs/user_guide/2_update_history/index.rst
- docs/bangc-docs/user_guide/3_overview/index.rst
- docs/bangc-docs/user_guide/9_operators/index.rst
> Docs modify

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxelization/voxelization.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxelization/voxelization_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxelization/voxelization_workspace.cpp
> [TEST](voxelization): add api check cases for voxelization

- bangc-ops/kernels/voxel_pooling_forward/voxel_pooling_forward.cpp
> [Fix](bangc-ops): mluOpVoxelPoolingForward check prams.

- bangc-ops/kernels/voxel_pooling_forward/voxel_pooling_forward.cpp
- docs/bangc-docs/design_docs/voxel_pooling_forward/voxel_pooling_forward.md
> [Fix](bangc-ops): Canceled the 0 element check.

- .github/pull_request_template.md
- tools/perf_analyse/README.md
Fix perf_analyse/README file and pr template
1）mlu_ops/tools/per_analyse/README.md
2）.github/pull_request_template.md
|        3       |         Layouts            |  NHWC …
> [Fix](bangc-ops):fix perf_analyse readme and pr template

- tools/perf_analyse/README.md
> [Feature](bangc-ops):fix mlu_ops to mlu-ops

- bangc-ops/kernels/debug.h
> [Feature](bangc-ops): sync debug.h.

- bangc-ops/kernels/box_iou_rotated/box_iou_rotated.cpp
- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_aligned.h
- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_nonaligned.h
- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_union1.mlu
- bangc-ops/kernels/box_iou_rotated/box_iou_rotated_utils.h
- bangc-ops/mlu_op.h
- bangc-ops/mlu_op_kernel.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/box_iou_rotated.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/box_iou_rotated.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/test_case/case_1.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/test_case/case_2.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/test_case/case_3.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/test_case/case_zero_element.prototxt
- docs/bangc-docs/design_docs/box_iou_rotated/box_iou_rotated.md
- docs/bangc-docs/design_docs/box_iou_rotated/pseudo_code
- docs/bangc-docs/user_guide/9_operators/index.rst
add new op box_iou_rotated
1) mlu-ops/bangc-ops/kernels/box_iou_rotated/*
2) mlu-ops/bangc-ops/mlu_op.h
3) mlu-ops/bangc-ops/mlu_op_kernel.h
5) mlu-ops/bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/*
6) mlu-ops/bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/box_iou_rotated/*
8) mlu-ops/docs/bangc-docs/user_guide/9_operators/*
9) mlu-ops/docs/bangc-docs/design_docs/box_iou_rotated/* …
> [Feature](bangc-ops): add box_iou_rotated op.

- bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto/mlu_op_test.proto
> [Feature](bangc-ops):change box_iou_rotated param id.

- bangc-ops/kernels/rotated_feature_align/rotated_feature_align_block.mlu
fix code to support nan/inf data for rois
1) mlu-ops/bangc-ops/kernels/rotated_feature_align/rotated_feature_align_block.mlu
|        3       |         Layouts            | …
> [Feature](bangc-ops):fix op support nan/inf

- .github/pull_request_template.md
> [Feature](bangc-ops):fix pr

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_crop_forward/roi_crop_forward.cpp
del roi_crop_forward.cpp some vlog codes
1)  bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_crop_forward/roi_crop_forward.cpp
|        3       |         Layouts …
> [Fix](bangc-ops):del some vlog

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/ball_query/ball_query.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/ball_query/ball_query_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/generate_proposals_v2/generate_proposals_v2.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/generate_proposals_v2/generate_proposals_v2_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/generate_proposals_v2/generate_proposals_v2_workspace.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/poly_nms/poly_nms.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/poly_nms/poly_nms_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/poly_nms/poly_nms_workspace.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/prior_box/prior_box.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/prior_box/prior_box_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/psroipool_backward/psroipool_backward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/psroipool_backward/psroipool_backward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/psroipool_forward/psroipool_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/psroipool_forward/psroipool_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roi_crop_backward/roi_crop_backward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roi_crop_backward/roi_crop_backward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roi_crop_forward/roi_crop_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/roi_crop_forward/roi_crop_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/three_interprolate_forward/three_interprolate_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/three_interprolate_forward/three_interprolate_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxel_pooling_forward/voxel_pooling_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxel_pooling_forward/voxel_pooling_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxelization/voxelization.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxelization/voxelization_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/voxelization/voxelization_workspace.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/yolo_box/yolo_box.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/yolo_box/yolo_box_general.cpp
> [TEST-25159]test(api_gtest): add sync

- .github/pull_request_template.md
- .github/workflows/bangcops_release_test.yaml
- .github/workflows/ci.yaml
- .github/workflows/daily.yaml
- bangc-ops/CMakeLists.txt
- bangc-ops/README.md
- bangpy-ops/README.md
- docs/MLU-OPS-Test-Report-Template.md
…ramework
|        2       |          Job …
> [Feature](bangc-ops): delete MLU270/MLU290 compile message and test framework

- bangc-ops/mlu_op.h
|        1       |          Supported hardware         | MLU370<br>MLU590|
|        2       |          Job types          |    block <br> U1 …
> [Docs](bangc-ops): Improved the doc

- .github/workflows/bangcops_release_test.yaml
- .github/workflows/ci.yaml
- .github/workflows/daily.yaml
- build.property
- docker/ubuntu18.04-x86_64/Dockerfile
- version_check.sh
|        1       |          Supported hardware         | MLU370<br>MLU590|
|        2       |          Job types          |    block <br> U1 …
> [Feature](bangc_ops): update cntookit 3.3.0.

- bangc-ops/test/mlu_op_gtest/pb_gtest/include/pb_test_tools.h
|        1       |Supported hardware                    |             MLU370<br>MLU590 …
> [Feature](bangc-ops): add some base function.

- .github/workflows/ci.yaml
- bangc-ops/CMakeLists.txt
- samples/bangc-ops/CMakeLists.txt
- samples/bangc-ops/abs_sample/CMakeLists.txt
- samples/bangc-ops/fault_sample/CMakeLists.txt
- samples/bangc-ops/poly_nms_sample/CMakeLists.txt
修复编译bangc-ops samples 依赖库的链接顺序引起编译失败的bug.
bangc-ops/CMakeLists.txt
samples/bangc-ops/CMakeLists.txt
samples/bangc-ops/abs_sample/CMakeLists.txt
samples/bangc-ops/fault_sample/CMakeLists.txt
samples/bangc-ops/poly_nms_sample/CMakeLists.txt
root@370X8-IB-64:/usr/local/neuware/samples/bangc-ops# bash build.sh 
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ …
> [Fix](bangc_ops): fix bangc-ops samples build.

- bangc-ops/mlu_op.h
- tools/format2google
fix the format of mlu_op.h
bangc-ops/mlu_op.h
tools/format2google
> [Fix](bangc-ops): fix mlu_op.h format.

- bangc-ops/kernels/add_n/add_n.cpp
Add missing cpp file for add_n ops
bangc-ops/kernels/kernel_wrapper/add_n/add_n.cpp
None
> [Feature](bangc-ops): add add_n files

- bangc-ops/core/gen_case.cpp
Fix gen_case func bug
1. /bangc-ops/core/gen_case.cpp
|        2       |Job types                             |          block <br> U1 <br> U4       |
|        3       |Layouts …
> [Bug] gen_case: fix genCaseData

- .github/pull_request_template.md
|        1       |Supported hardware                    |             MLU370<br>MLU590 …
> [Fix](docs) fix pr style

- bangc-ops/CMakeLists.txt
- bangc-ops/README.md
- bangc-ops/build.sh
- bangc-ops/gen_symbol_visibility_map.py
- 重命名gen_mluops.py 和生成的libmluops.map 的文件名
- 重命名gen_mluops.py 为  gen_symbol_visibility_map.py
- 修改生成的libmluops.map文件名 为 symbol_visibility.map
- 修改编译脚本build.sh 和 CMakeList.txt
- 修改README.md
> [Feature](bangc-ops):rename gen_mluops.py and libmluops.map file

- bangc-ops/kernels/indice_convolution_backward_data/indice_convolution_backward_data.cpp
- bangc-ops/mlu_op.h
- docs/bangc-docs/design_docs/indice_convolution_backward_data/indice_convolution_backward_data.md
update docs and code.
modified:   bangc-ops/kernels/indice_convolution_backward_data/indice_convolution_backward_data.cpp
modified:   docs/bangc-docs/design_docs/indice_convolution_backward_data/indice_convolution_backward_data.md
不涉及功能改变。
测试结果：
```C++
[----------] 127 tests from indice_convolution_backward_data/TestSuite (3306 ms total)
[ SUMMARY  ] Total 127 cases of 1 op(s).
ALL PASSED.
[==========] 127 test cases from 1 test suite ran. (3634 ms total)
[  PASSED  ] 127 test cases.
```
> [Feature](bangc-ops): update indice_convolution_backward_data docs and code

- docs/bangc-docs/user_guide/9_operators/index.rst
Update user guide about indice_convolution_backward_data
modify docs/bangc-docs/user_guide/9_operators/index.rst
> [Docs](bangc-ops): update indice_convbpdata user guide

- bangc-ops/kernels/deform_roi_pool/deform_roi_pool.cpp
[MLUOP] [Error]:[mluOpDeformRoiPoolForward] Zero element tensor failure
[MLUOP] [Error]:[mluOpDeformRoiPoolBackward] Zero element tensor failure
Please give a brief overview here, if you want to note and summarize the content.
> [Fix](bangc-ops): fix the log error.

- bangc-ops/mlu_op.h
> [Docs](bangc-ops): update indice_convpbdata api comments

- docs/bangc-docs/BANGC-OPS-Operator-Design-Doc-Template.md
> [Fix](bangc-ops): update BANGC-OPS-Operator-Design-Doc-Template.md

- bangc-ops/mlu_op.h
> [Doc](bangc-ops) add get indice pairs docs

- docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
修改算子开发文档中一些问题
1）docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
> [Docs](bangc-ops):fix docs

- docs/GTest-User-Guide-zh.md
- docs/MLU-OPS-Test-Report-Template.md
- docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
修改了 mlu_ops 仓库中一些文档内容
1）docs/GTest-User-Guide-zh.md
2）docs/MLU-OPS-Test-Report-Template.md
> [Docs](bangc-ops):fix gtest docs and test report docs

- bangc-ops/kernels/indice_convolution_backward_data/indice_convolution_backward_data.cpp
>  [Feature](bangc-ops): update platform-arch check for indice convbpdata

- bangc-ops/kernels/indice_convolution_backward_data/indice_convolution_backward_data.cpp
> [Feature](bangc-ops): update platform-arch check for indice convbpdata

- bangc-ops/mlu_op.h
> [Docs](bangc-ops): Fixed the doc

- docs/bangc-docs/user_guide/9_operators/index.rst
modify 9_operators/index.rst
|----------------|--------------------------------------|---------- …
> [Docs](bangc-ops): fix doc

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/bangpy_ci.yaml
> [Feature](mlu-ops): have bangc and bangc ci working sperately.

- README.md
- docs/Gencase-User-Guide-zh.md
给mlu-ops仓库添加常用的环境变量和gen_case的使用文档
1）./README.md
2）docs/Gencase-User-Guide-zh.md
> [Docs](bangc-ops): add mlu-ops gen_case file

- bangc-ops/mlu_op.h
- docs/bangc-docs/user_guide/9_operators/index.rst
> [Docs](bangc-ops):Fixed doc problems

- bangc-ops/mlu_op.h
规范mlu_op.h文件注释内容
1) bangc-ops/mlu_op.h
> [Docs](bangc-ops):fix mlu_op.h

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2_union1.mlu
Fix the return of roi_num in the generate-proposals_v2 operator problem.
bangc_ops/kernels/generate_proposals_v2/generate_proposals_v2_union1.mlu
generate_proposals_v2是复合类算子。<br>
rpn_rois参数精度设为 diff1 <= 3e-3 && diff2 <=3e-3。<br>
rpn_roi_probs、rpn_rois_num、rpn_rois_batch_size的精度设置为 diff3=0。
| No.  | Details                                | Check Results              |
| ---- | -------------------------------------- | -------------------------- |
| 1    | Supported hardware                     | MLU290<br>MLU370<br>MLU590 |
| 2    |                                        | U1 …
> [Feature](bangc-ops): fix generate_proposals_v2's abnormal value of roi_nums

- bangc-ops/mlu_op.h
规范 mlu-ops仓 r0.4分支的mlu_op.h接口注释
1）bangc-ops/mlu_op.h
> [Docs](bangc-ops): fix mlu_op.h

- bangc-ops/mlu_op.h
Modify poly_nms interface comments
mlu_op.h
> [Feature](bangc-ops): modify poly_nms interface comments

- bangc-ops/mlu_op.h
> [Fix](bangc-ops): Repair spelling errors in notes.

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2_union1.mlu
- bangc-ops/mlu_op.h
> [Fix](bangc-ops): fix bug and spelling errors.

- bangc-ops/core/context.cpp
> [Feature](bangc-ops): sup mlu590

- docs/bangc-docs/user_guide/2_update_history/index.rst
fix release-note
- mlu-ops/docs/bangc-docs/user_guide/2_update_history/index.rst
> [Docs](bangc-ops): fix relase-note

- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
> [Docs](bangc-ops): fix date-order in changlog

- .github/pull_request_template.md
- docs/MLU-OPS-Test-Report-Template.md
完善 mlu-ops master 分支 文档
1）modified:   .github/pull_request_template.md
2）modified:   docs/MLU-OPS-Test-Report-Template.md
> [Docs](bangc-ops):fix mlu-ops docs

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/bangpy_ci.yaml
- .gitignore
- README.md
renamed:    .github/workflows/bangcops_release_test.yaml -> .github/workflows/bangc_all_system_ci.yaml
renamed:    .github/workflows/ci.yaml -> .github/workflows/bangc_ci.yaml
new file:   .github/workflows/bangpy_ci.yaml
modified:   .gitignore
> [Fix](bangc-ops): have ci work seprately for r0.5.

- .github/pull_request_template.md
- README.md
- docs/GTest-User-Guide-zh.md
- docs/Gencase-User-Guide-zh.md
- docs/MLU-OPS-Test-Report-Template.md
- docs/bangc-docs/BANGC-OPS-Operator-Design-Doc-Template.md
- docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
根据mlu-ops的master分支文档内容，刷新 r0.5分支的文档
1）modified:   .github/pull_request_template.md
2）modified:   README.md
3）modified:   docs/GTest-User-Guide-zh.md
4）new file:   docs/Gencase-User-Guide-zh.md
5）modified:   docs/MLU-OPS-Test-Report-Template.md
6）modified:   docs/bangc-docs/BANGC-OPS-Operator-Design-Doc-Template.md
7）modified:   docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
> [Docs](bangc-ops):fix r0.5 docs

- bangc-ops/mlu_op.h
> [Feature](bangc-ops): fix moe_dispatch_backward_data api guide.

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/nms_rotated/nms_rotated.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/nms_rotated/nms_rotated_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/nms_rotated/nms_rotated_workspace.cpp
Check nms_rotated param.
Add nms_rotated param check cases
> TEST(bangc-ops): add nms_rotated api check cases

- bangc-ops/kernels/moe_dispatch_backward_data/moe_dispatch_backward_data.cpp
- docs/bangc-docs/design_docs/moe_dispatch_backward_data/moe_dispatch_backward_data.md
> [Feature](bangc-ops): fix moe_dispatch_backward_data api check.

- bangc-ops/core/gen_case.cpp
修改 gen_case 保存二进制真值
1) modified:   bangc-ops/core/gen_case.cpp
> [Fix](bangc-ops):fix gen_case

- README.md
add libprotobuf version restriction info to read.me
READ.ME
> [Fix](bangc-ops): add libprotobuf version restriction info to read.me.

- bangc-ops/kernels/psroipool/psroipool_block.mlu
修改 psroipool算子标量计算中四舍五入方式，例如 对于 2.5这个数据
修改前：MLU：__float2int_rn(2.5) = 2； GPU/CPU：round(2.5) = 3; 无法对齐
修改后：MLU：__float2int_rd(2.5) = 3； GPU/CPU：round(2.5) = 3; 可以对齐
1）modified: bangc-ops/kernels/psroipool/psroipool_block.mlu
|----------------|--------------------------------------|------------------------ …
> [Fix](bangc-ops):fix psroipool __float2int_rn to __float2int_rd

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/daily.yaml
CI submodule check fail， fix the ci bug.
modified:   .github/workflows/bangc_ci.yaml
modified:   .github/workflows/daily.yaml
all ci workflow should pass.
> [Fix](bangc-ops): fix submodule ci bug.

- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/kernels/roi_align_backward/roi_align_backward.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/roi_align_backward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/roi_align_backward.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/test_case/case_1.prototxt
- docs/bangc-docs/user_guide/9_operators/index.rst
roi_align_backward二进制适配mlu-ops
change bangc-ops/kernels/kernel_wrapper/lib/libextops.a
create bangc-ops/kernels/roi_align_backward/roi_align_backward.cpp
create bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/roi_align_backward.cpp
create bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/roi_align_backward.h
create bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/test_case/case_0.prototxt
create bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/test_case/case_1.prototxt
For static threshold standard details, see: …
> [Feature](bangc-ops):add roi_align_backward binary op

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/daily.yaml
- build.property
update cntoolkit 3.4.1 and docker ci yaml.
见文件修改列表.
使用 precheckin 流水进行测试。
> [Feature](bangc-ops):update cntoolkit 3.4.1 and docker ci yaml.

- README.md
- docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
- docs/pr.md
Update submodule info to READ.ME, pr.md and develop process.
modified:   docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
modified:   docs/pr.md
> [Feature](bangc-ops): update read.me, pr and develop process with submodule info.

- docs/bangc-docs/user_guide/9_operators/index.rst
> [Feature](bangc-ops): add nms userguide & modify roi_align_forward userguide

- docs/bangc-docs/user_guide/9_operators/index.rst
> [Docs](bangc-ops): fix points_in_boxes index rst

- .github/workflows/bangc_all_system_ci.yaml
fix check version 0.6.0
No test
> [Fix](bangc-ops): fix check version

- docs/bangc-docs/user_guide/2_update_history/index.rst
- docs/bangc-docs/user_guide/9_operators/index.rst
Improve the User Guide.
Modify Section 9.
no test.
> [Docs](bangc-ops):Fixed doc problems (#608)

- README.md
- docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
- docs/pr.md
update submodule info.
modified:   docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
modified:   docs/pr.md
> [Feature](bangc-ops): r0.4 update read.me, pr and develop process with submodule info.

- docs/bangc-docs/design_docs/get_indice_pairs/get_indice_pairs.md
删除get_indice_pairs 敏感词
docs/bangc-docs/design_docs/get_indice_pairs/get_indice_pairs.md
删除敏感词
文档修改，无需测试
| …
> [Docs](bangc-ops) : delete get_indice_pairs sensitive words

- docs/GTest-User-Guide-zh.md
fix code coverage docs
modified:   docs/GTest-User-Guide-zh.md
> [Docs](bangc-ops): fix code coverage

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/nms/nms.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/nms/nms.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/nms/nms3D_utils.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roialign_forward/roialign_forward.cpp
Update the nms and roialign_forward operator's gtest license.
The gtest license content of the nms and roialign_forward.
> [Docs](bangc-ops): update the License for nms and roialign_forward.

- bangc-ops/mlu_op.h
- docs/bangc-docs/design_docs/psroipool_backward/psroipool_backward.md
- docs/bangc-docs/design_docs/psroipool_forward/psroipool_forward.md
完善psroipool算子文档
1）modified:   bangc-ops/mlu_op.h
2）modified:   docs/bangc-docs/design_docs/psroipool_backward/psroipool_backward.md
3）modified:   docs/bangc-docs/design_docs/psroipool_forward/psroipool_forward.md
> [Fix](bangc-ops):fix psroipool docs

- bangc-ops/mlu_op.h
- docs/bangc-docs/design_docs/points_in_boxes/points_in_boxes.md
modified:   docs/bangc-docs/design_docs/points_in_boxes/points_in_boxes.md
> [Feature](bangc-ops): fix doc bug

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/ms_deform_attn_backward/ms_deform_attn_backward_general.cpp
> [Fix](bangc-ops): fix ms_deform_attn_backward api testcase

- docs/bangc-docs/api_guide/update.rst
- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
None.
Relies on further tests.
Please give a brief overview here, if you want to note and summarize the content.
> [Feature](bangc-ops): Update spec files for v0.7.0

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/mutual_information_backward/mutual_information_backward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/mutual_information_backward/mutual_information_backward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/mutual_information_backward/mutual_information_backward_workspace.cpp
> [TEST](bangc-ops): add mutual_information_backward api test

- docs/bangc-docs/user_guide/9_operators/index.rst
fix mutual_information doc
docs/bangc-docs/user_guide/9_operators/index.rst
None.
> [Fix](bangc-ops): fix mutual_information doc

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/diff_iou_rotated_sort_vertices_forward/diff_iou_rotated_sort_vertices_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/diff_iou_rotated_sort_vertices_forward/diff_iou_rotated_sort_vertices_forward_general.cpp
> [TEST](bang-ops):add diff_iou_rotated_sort_vertices_forward api test

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/focal_loss_sigmoid_backward/focal_loss_sigmoid_backward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/focal_loss_sigmoid_backward/focal_loss_sigmoid_backward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward_general.cpp
> [TEST](bangc-ops): add focal_loss_sigmoid api test

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward_workspace.cpp
> [TEST](bangc-ops): add dynamic_point_to_voxel_forward api test

- .github/pull_request_template.md
- docs/MLU-OPS-Performance-Acceptance-Standard.md
> [Docs](bangc-ops):update mlu-only mode

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp
[Feature](bangc-ops): fix memory leak
[Please briefly describe what modification is made in this pull request, and indicate where to make the modification.](modified:   ../test/mlu_op_gtest/pb_gtest/src/zoo/dynamic_point_to_voxel_forward/dynamic_point_to_voxel_forward.cpp) …
> [Fix](bangc-ops): Dynamic point to voxel fix mm leak

- bangc-ops/README.md
- bangc-ops/independent_build.sh
Add paralell jobs option for build.
> [Feature](bangc-ops): Add concurrent build jobs

- docs/bangc-docs/user_guide/9_operators/index.rst
fix add_n in uesr_guide
modified:   docs/bangc-docs/user_guide/9_operators/index.rst
None, 仅文档修改
> [Fix](bangc-ops): fix add_n in uesr_guide

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/focal_loss_sigmoid_backward/focal_loss_sigmoid_backward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/focal_loss_sigmoid_forward/focal_loss_sigmoid_forward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/prior_box/prior_box_general.cpp
> [Fix](bangc-ops): fix api gtest

- docs/bangc-docs/user_guide/12_faq/index.rst
update FAQ in user guide
[Please briefly describe what modification is made in this pull request, and indicate where to make the modification.](modified:   ../../docs/bangc-docs/user_guide/12_faq/index.rst)
None，修改仅涉及文档
> [Feature](bangc-ops): update FAQ in user guide

- tools/check_log_error.py
- tools/pre-commit
update pre-commit and ci.
tools/pre-commit
tools/check_log_error.py
> [Fix](bangc-ops): update ci code format check r07.

- tools/check_log_error.py
- tools/pre-commit
update pre-commit tools
tools/pre-commit
tools/check_log_error.py
> [Fix](bangc-ops): update ci code format check.

- bangc-ops/kernels/focal_loss_sigmoid/focal_loss_sigmoid.cpp
> [Fix](bangc-ops): fix focal_loss log

- bangc-ops/kernels/voxelization/voxelization.cpp
Fix zero element bug
bangc-ops/kernels/voxelization/voxelization.cpp
> [Fix](bangc-ops):voxelization zero tensor bug fix.

- bangc-ops/mlu_op.h
Correct tin_shift api guide.
bangc-ops/mlu_op.h.
> [Feature](bangc-ops): recorrect tin_shift api guide

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/tin_shift_backward/tin_shift_backward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/tin_shift_backward/tin_shift_backward.general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/tin_shift_forward/tin_shift_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/tin_shift_forward/tin_shift_forward_general.cpp
> [TEST](bangc-ops): add tin_shift api test

- bangc-ops/mlu_op.h
> [Fix](bangc-ops): fix interface-note

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2_union1.mlu
generate_proposals_v2 support nan/inf cases.
bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2_union1.mlu
> [Feature](bangc-ops):generate_proposals_v2 support nan/inf cases.

- bangc-ops/kernels/dynamic_point_to_voxel_backward/dynamic_point_to_voxel_backward.cpp
- bangc-ops/mlu_op.h
fix missing return value of interface
mlu_op.h
> [Fix](bangc-ops):fix missing return value of interface

- bangc-ops/mlu_op.h
Repair interface description error.
bangc-ops/mlu_op.h.
> [Fix](bangc-ops):Repair interface description error.

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.cpp
Modify scale limit from 0.5G num to 2G num.
bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2.cpp
> [Feature](bangc-ops):Modify scale limit from 0.5G num to 2G num

- bangc-ops/kernels/abs/abs.cpp
- bangc-ops/kernels/abs/abs.h
- bangc-ops/kernels/abs/abs_block.mlu
370X4
./independent_build.sh  --filter="abs" -d,  cpu case pass
./independent_build.sh  --filter="abs",  cpu case pass
> [Fix](bangc-ops): fix return-status in kernel-func

- bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2_union1.mlu
fix generate_proposals_v2 buffer overflow.
bangc-ops/kernels/generate_proposals_v2/generate_proposals_v2_union1.mlu
> [Fix](bangc-ops):Fix generate_proposals_v2 buffer overflow.

- samples/bangc-ops/build.sh
- samples/bangc-ops/env.sh
revise sample compile shell script for local compiling user friendly
modified:   samples/bangc-ops/build.sh
modified:   samples/bangc-ops/env.sh
sample compiled successfully and test passed.
> [Fix](bangc-ops): revise sample compile shell script for local compiling user friendly

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/daily.yaml
- build.property
Update toolkit version to 3.6.1.
build.property
See CI test result for detail.
> [Feature](bangc-ops): Update toolkit to 3.6.1.

- .gitattributes
Syntax highlight support for mlu files to provide better reading experience on web frontend.
new file: .gitattributes
Apperence change for web frontend. See CI test result for more details.
> [Feature](bangc-ops): add syntax highlight

- bangc-ops/mlu_op.h
> [Fix](bangc-ops): add scale limitation in mlu_op.h

- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/border_align_backward/border_align_backward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/border_align_backward/border_align_backward_general.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/border_align_forward/border_align_forward.cpp
- bangc-ops/test/mlu_op_gtest/api_gtest/src/gtest/border_align_forward/border_align_forward_general.cpp
> [TEST](bangc-ops): add border_align api test

- docs/bangc-docs/user_guide/9_operators/index.rst
Fix doc bug.
modified:  /docs/bangc-docs/user_guide/9_operators/index.rst
Doc modification. No need for test report. See CI test for more details.
> [Docs](bangc-ops): Fix a bug of docs.

- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/kernels/roi_pooling_backward/roi_pooling_backward.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/roi_pooling_backward.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/roi_pooling_backward.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/test_case/case_0.prototxt
- docs/bangc-docs/user_guide/9_operators/index.rst
Add new op roi_pooling_backward.
create bangc-ops/kernels/roi_pooling_backward/roi_pooling_backward.cpp
create bangc-ops//test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/roi_pooling_backward.cpp
create bangc-ops//test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/roi_pooling_backward.h
create bangc-ops//test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/test_case/case_0.prototxt
change bangc-ops/mlu_op.h
change docs/bangc-docs/user_guide/9_operators/index.rst
change bangc-ops/kernels/kernel_wrapper/lib/libextops.a
change bangc-ops/kernels/kernel_wrapper/wrapper.h
If you want to know how to do operator testing, you can see [GTest-User-Guide-zh](https://github.com/Cambricon/mlu-ops/blob/master/docs/GTest-User-Guide-z …
> [Feature](bangc-ops): new op roi_pooling_backward

- .github/pull_request_template.md
> [Docs](bangc-ops): update pr_template

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/daily.yaml
- build.property
- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
- installer/independent/debian/changelog
Update docs for v0.8.1
modified:   .github/workflows/bangc_ci.yaml
modified:   .github/workflows/daily.yaml
modified:   installer/independent/debian/changelog
No test.
> [Docs](bangc-ops): Fix docs for v0.8.1.

- bangc-ops/mlu_op.h
modify the documentation comments of mlu_op.h
file changed : mlu_op.h
> [Docs](bangc-ops):modify the documentation comments of mlu_op.h

- docs/MLU-OPS-Performance-Acceptance-Standard.md
Update performance acceptance standard.
modified:   docs/MLU-OPS-Performance-Acceptance-Standard.md
Document update.
> [Docs](bangc-ops): Update performance acceptance standard.

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/bangc_ci.yaml
- .github/workflows/daily.yaml
- bangc-ops/mlu_op.h
- build.property
> [Feature](bangc-ops): upgrade to toolkit3.7.0

- installer/centos7.5/SPECS/mluops-independent.spec
- installer/centos7.5/SPECS/mluops.spec
- installer/independent/debian/changelog
update installer files with the newest version
modified:   installer/independent/debian/changelog
> [Docs](bangc-ops): update installer version message

- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/kernels/strided_slice/strided_slice.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/strided_slice/strided_slice.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/strided_slice/strided_slice.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/strided_slice/test_case/case_0.prototxt
- docs/bangc-docs/user_guide/9_operators/index.rst
将strided_slice算子以二进制形式合入mluops
增加算子strided_slice
- diff3
- Job types
```bash
Please fill your test results(Error Message) in …
```
> [Feature](bangc-ops): add strided_slice binary operator.

- docs/bangc-docs/user_guide/2_update_history/index.rst
> [Fix](bangc-ops): fix release note in v0.9.0.

- bangc-ops/kernels/kernel_wrapper/wrapper.h
- bangc-ops/kernels/pad/pad.cpp
- bangc-ops/mlu_op.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/pad.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/pad.h
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_0.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_1.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_2.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_3.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_4.prototxt
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/pad/test_case/case_5.prototxt
- docs/bangc-docs/user_guide/9_operators/index.rst
将pad算子以二进制形式合入mluops。
新增pad算子
- diff3
- Job types
```bash
Please fill your test results(Error Message) in here, ...
```
Test Point-2: `Whether illegal parameters are passed`. Acceptance Standard: …
> [Feature](bangc-ops): add pad op

- bangc-ops/core/gen_case.cpp
- bangc-ops/mlu_op.h
update mluOpSetGenCaseMode declear in mlu_op.h
> [Docs](bangc-ops): update mluOpSetGenCaseMode declear in mlu_op.h

- .github/ci_script/combine_log.py
- .github/ci_script/file_guard.py
- .github/ci_script/mlu-ops-all_system_test_script.sh
- .github/ci_script/mlu-ops-ci_script.sh
- .github/workflows/bangc_ci.yaml
Customize CI process.
new file:   ci_script/combine_log.py
new file:   ci_script/file_guard.py
new file:   ci_script/mlu-ops-all_system_test_script.sh
new file:   ci_script/mlu-ops-ci_script.sh
modified:   workflows/bangc_ci.yaml
Test in CI. See CI report for details.
> [Feature](mlu-ops): Customize CI.

- bangc-ops/kernels/points_in_boxes/points_in_boxes.cpp
add fool_check for points_in_boxes
> [Fix](bangc-ops):add fool_check for points_in_boxes

- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/nms/nms.cpp
- bangc-ops/test/mlu_op_gtest/pb_gtest/src/zoo/nms/nms.h
Update binary-ops to v1.22.0.
modified:   kernels/kernel_wrapper/lib/libextops_0.a
modified:   kernels/kernel_wrapper/lib/libextops_1.a
modified:   kernels/kernel_wrapper/lib/libextops_2.a
modified:   kernels/kernel_wrapper/lib/libextops_3.a
modified:   kernels/kernel_wrapper/lib/libextops_4.a
modified:   kernels/kernel_wrapper/lib/libextops_5.a
Binary ops update, see CI test result for more details.
Update binary ops version to v1.22.0.
> [Feature](bangc-ops): Update binary-ops to v1.22.0.

- bangc-ops/kernels/yolo_box/yolo_box.cpp
- bangc-ops/mlu_op.h
- docs/bangc-docs/design_docs/yolo_box/yolo_box.md
yolo_box 设计文档描述不完备：仅 iou_aware 为 false 时， iou_aware_factor 参数可以是 nan/inf 。
1. 修改 yolo_box 设计文档。
2. 增加 iou_aware_factor 的参数的防呆。
> [Feature](bangc-ops): fix yolo_box bug, add iou_aware_factor param_check, and fix design docs

- .github/workflows/bangc_all_system_ci.yaml
- .github/workflows/daily.yaml
> [Fix](bangc-ops): revise the image for daily and all system ci.

- installer/independent/debian/rules
> [Fix](bangc-ops): revise debian rules for package.

- .github/workflows/bangc_all_system_ci.yaml
删除无用 .a 文件
deleted:    bangc-ops/kernels/kernel_wrapper/lib/libextops_0.a
deleted:    bangc-ops/kernels/kernel_wrapper/lib/libextops_1.a
deleted:    bangc-ops/kernels/kernel_wrapper/lib/libextops_2.a
deleted:    bangc-ops/kernels/kernel_wrapper/lib/libextops_3.a
deleted:    bangc-ops/kernels/kernel_wrapper/lib/libextops_4.a
deleted:    bangc-ops/kernels/kernel_wrapper/lib/libextops_5.a
> [Feature](bangc-ops): delete useless *.a files.

- build.property
build.property 中对应的 mlu-ops 版本更新
> [Docs](bangc-ops): update build.property for 0.11.0

- installer/centos7.5/SPECS/mluops-independent.spec
> [Docs](bangc-ops): update centos changelog for 0.11.0

- README.md
> [Fix](bangc-ops): fix cntoolkit install method.

- independent_build.sh
Daily package failed
daily package passed
> [Fix](mlu-ops): fix daily package failure.

- test/mlu_op_gtest/pb_gtest/src/executor.cpp
- test/mlu_op_gtest/pb_gtest/src/gtest/test_env.cpp
> [Feature](mlu-ops): fix driver-process error.

- .github/workflows/mluops_all_system_ci.yaml
> [Fix](mlu-ops): add build property all system check.

- independent_build.sh
modify python to python3
ci passed
> [Fix](mlu-ops): fix python to python3 in independent_build

- test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Add real data related op poly_nms into test_list.
test/mlu_op_gtest/pb_gtest/gtest_config/test_list.
- diff1
- diff2
- diff3
- Job types
Test Point-1: `When a new operator is submitted, the test …
> [Fix](mluOpPolyNms):Add real data related op poly_nms into test_list.

- test/mlu_op_gtest/pb_gtest/gtest_config/test_list
Add diff_iou_rotated api name to test_list
test/mlu_op_gtest/pb_gtest/gtest_config/test_list
--mlu_only test passed
> [Fix](mluOpDiffIouRotatedSortVerticesForward): Add diff_iou_rotated api name to test_list

- docs/user_guide/9_operators/index.rst
fix docs error.
docs/user_guide/9_operators/index.rst
- diff1
- diff2
- diff3
- Job types
Test Point-1: `When a new operator is submitted, the test points are given and the test results are …
> [Docs](mlu-ops):update operators index.rst.

- kernels/border_align/border_align_backward/border_align_backward.cpp
- kernels/border_align/border_align_forward/border_align_forward.cpp
- kernels/sqrt/sqrt.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/border_align_forward/test_case/border_align_forward_0.prototxt
- test/mlu_op_gtest/pb_gtest/src/zoo/sqrt/sqrt.cpp
> [Fix](mluOpSqrt,mluOpBorderAlignForward): fix gen-case.

- docs/design_docs/adam_w/adam_w.md
- kernels/adam_w/adam_w.cpp
- kernels/adam_w/adam_w.h
- kernels/adam_w/adam_w_union1.mlu
- mlu_op.h
- test/mlu_op_gtest/pb_gtest/src/zoo/adam_w/adam_w.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/adam_w/adam_w.h
- test/mlu_op_gtest/pb_gtest/src/zoo/adam_w/test_case/case_0.prototxt
> [Feature](mluOpAdamW): add new op

- .github/workflows/daily.yaml
- .github/workflows/mluops_all_system_ci.yaml
> [Fix](mlu-ops): Fix ci docker setting.

- cmake/generate_package_info.cmake
- docs/api_guide/update.rst
- docs/user_guide/2_update_history/index.rst
cmake/generate_package_info.cmake
Fix do package fail when only revise build.property mluops version.
- diff1
- diff2
- diff3
- Job types
If you have checked the following items, …
> [Feature](mlu-ops): Adapt compiling to version change in build.property.

- independent_build.sh
- installer/centos7.5/SPECS/mluops-independent.spec
> [Fix](mlu-ops): Fix the softlink relation in rpm package.

- test/mlu_op_gtest/include/math_half.h
Fix kylin compiling error.
test/mlu_op_gtest/include/math_half.h
- diff1
- diff2
- diff3
- Job types
Test …
> [Fix](mlu-ops): Fix compiling error on Kylin

- test/mlu_op_gtest/include/math_half.h
Fix kylin compiling error on r1.1 branch
test/mlu_op_gtest/include/math_half.h
Are new test cases added? If so, please post the correspo
nding generator-PR link here.
- diff1
- diff2
- diff3
- Job types
If you have checked the following items, please tick the relevant …
> [Fix](mlu-ops): Fix kylin compiling error on r1.1 branch.

- .github/ci_script/combine_log.py
- .github/ci_script/file_guard.py
- .github/ci_script/mlu-ops-ci_script.sh
Update CI scripts to support new CI test workflow.
modified:   .github/ci_script/mlu-ops-ci_script.sh
See test result for details.
> [Feature](mlu-ops): Update CI script.

- .github/ci_script/mlu-ops-ci_script.sh
Let CI test print more information.
modified:   .github/ci_script/mlu-ops-ci_script.sh
Check CI result.
> [Fix](mlu-ops): Fix CI print message.

- kernels/utils/philox_generator.h
add a device func to generator random numbers in philox mode.
add philox_generator.h in utils.
> [Feature](mlu-ops): add philox generator

- test/mlu_op_gtest/pb_gtest/include/evaluator.h
- test/mlu_op_gtest/pb_gtest/src/executor.cpp
- test/mlu_op_gtest/pb_gtest/src/gtest/mlu_op_gtest.cpp
Please give a brief overview here, if you want to note and summarize the content.
> [Test](mlu-ops): Improve gtest perf test output log

- docs/BANG C OPS-Develop-Guide.md
modify some spell error.
```
docs/BANG C OPS-Develop-Guide.md
```
> [Docs](mlu-ops):fix spell error.

- test/mlu_op_gtest/pb_gtest/src/zoo/deform_roi_pool_backward/deform_roi_pool_backward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/deform_roi_pool_backward/deform_roi_pool_backward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_backward/roi_align_rotated_backward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_backward/roi_align_rotated_backward.h
- test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_forward/roi_align_rotated_forward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_rotated_forward/roi_align_rotated_forward.h
受真值影响算子的理论计算量获取有误.
逐作用域分别计数，复用 cpuCompute 逻辑得到计算量.
> [Fix](mlu-ops): fix roi_align_rotated and deform_roi_pool3d_backward theory_ops

- README.md
- build.property
> [Feature](mlu-ops): upgrade toolkit and cnnl.

- kernels/generate_proposals_v2/generate_proposals_v2.cpp
- mlu_op.h
- test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.cpp
fix generate_proposals_v2 core dump bug.
modified:   kernels/generate_proposals_v2/generate_proposals_v2.cpp
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.cpp
> [Fix](mluOpGenerateProposalsV2):fix generate_proposals_v2 core dump bug.

- kernel_depends.toml
> [Fix](mluOpExecFFT): fix fft compile bug.

- test/mlu_op_gtest/api_gtest/src/gtest/active_rotated_filter_forward/active_rotated_filter_forward_general.cpp
- test/mlu_op_gtest/api_gtest/src/gtest/ball_query/ball_query_general.cpp
- test/mlu_op_gtest/api_gtest/src/gtest/border_align_backward/border_align_backward_general.cpp
- test/mlu_op_gtest/api_gtest/src/gtest/border_align_forward/border_align_forward_general.cpp
> [Test](mlu-ops):add stride api gtest case

- kernels/generate_proposals_v2/generate_proposals_v2.cpp
- kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
- test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.cpp
Fix gpv2 workspace interface incorrect usage problem
kernels/generate_proposals_v2/generate_proposals_v2.cpp
test/mlu_op_gtest/pb_gtest/src/zoo/generate_proposals_v2/generate_proposals_v2.cpp
> [Fix](mluOpGenerateProposalsV2): fix core dump.

- CMakeLists.txt
- independent_build.sh
Add -p(readperf) compile option be used to analysis performance.
modify CMakeLists.txt
modify independent_build.sh
> [Feature](mlu-ops):add -p(readperf) compile option

- core/logging.h
> [Fix](mlu-ops): Recover mlu_opcheck in logging.

- CMakeLists.txt
- README.md
- build.property
- core/cnlog.cpp
- independent_build.sh
- test/mlu_op_gtest/CMakeLists.txt
- tools/pre-commit
- version_pre_check.py
LOG/VLOG support timestamp and cardID
modified:   CMakeLists.txt
modified:   core/cnlog.cpp
modified:   test/mlu_op_gtest/CMakeLists.txt
modified:   independand.sh
> [Feature](mlu-ops):update log format use fmtlib.

- docs/design_docs/lgamma/lgamma.md
add document for new operator lgamma
add new file docs/design_docs/lgamma/lgamma.md
not yet
- diff1
- diff2
- diff3
- [*] MLU370
- Job types
- [*] BLOCK
```bash
Please fill your test results(Error Message) in …
```
> [Docs](mluOpLgamma): add docs for new operator lgamma

- docs/design_docs/logspace/logspace.md
> [Docs](mluOpLogspace): Add logspace doc

- CMakeLists.txt
- samples/mlu-ops/build.sh
fix sample compile error with link libmlu-ops.a
CMakeLists.txt
samples/mlu-ops/build.sh
> [Feature](mlu-ops):fix sample compile.

- kernels/ball_query/ball_query_union1.mlu
- kernels/ms_deform_attn/ms_deform_attn_backward/ms_deform_attn_backward_fast_union1.mlu
- kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_utils.h
- kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
- kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_small_channel_union1.mlu
- kernels/roiaware_pool3d/roiaware_pool3d_union1.mlu
- kernels/roipoint_pool3d/roipoint_pool3d_union1.mlu
- kernels/roipoint_pool3d/roipoint_pool3d_union1_large_boxes_num.mlu
- kernels/sparse_conv/get_indice_pairs/get_indice_pairs_block.mlu
bang_collect 将被弃用
使用 bang_filter 替换 bang_collect
> [Feature](mlu-ops): use bang_filter replace to bang_collect/select

- test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/roi_align_backward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/roi_pooling_backward.cpp
ix gtest bug in mlu_only mode
test/mlu_op_gtest/pb_gtest/src/zoo/roi_align_backward/roi_align_backward.cpp
test/mlu_op_gtest/pb_gtest/src/zoo/roi_pooling_backward/roi_pooling_backward.cpp
> [Fix](mluOpRoiPoolingBackward):fix gtest bug.

- build.property
Update CNNL version to v1.27.0
> [Feature](mlu-ops): Update CNNL version to v1.27.0.

- docs/design_docs/lgamma/lgamma.md
> [Fix](mluOpLgamma): fix formula in lgamma doc

- .github/scripts/run_ci_test.py
Fix merge test fail of master branch.
modified:   .github/scripts/run_ci_test.py
> [Fix](mlu-ops): Fix master test fail when PR merged.

- kernels/logspace/logspace.cpp
- kernels/logspace/logspace.h
- kernels/logspace/logspace_block.mlu
- mlu_op.h
- test/mlu_op_gtest/pb_gtest/src/zoo/logspace/logspace.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/logspace/logspace.h
- test/mlu_op_gtest/pb_gtest/src/zoo/logspace/test_case/logspace_data_included_float32_1725532639524.prototxt
> [Feature](mluOpLogspace) add new operator logspace.

- docs/MLU-OPS-OpList.md
- docs/design_docs/lgamma/lgamma.md
- docs/user_guide/9_operators/index.rst
Add logspace/lgamma in rst and op_list.
docs/MLU-OPS-OpList.md
docs/design_docs/lgamma/lgamma.md
docs/user_guide/9_operators/index.rst
> [Docs](mlu-ops): Add logspace/lgamma in rst and op_list.

- test/mlu_op_gtest/api_gtest/src/gtest/mutual_information_forward/mutual_information_forward_general.cpp
> [Fix](mlu-ops):Fix mutual information forward case error

- core/cnlog.cpp
- core/context.cpp
modify MLUOP to MLU-OPS in log.
core/cnlog.cpp
core/context.cpp
> [Fix](mlu-ops):modify MLUOP to MLU-OPS in log.

- kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
- kernels/generate_proposals_v2/generate_proposals_v2_union1_500.mlu
- kernels/rotated_feature_align/rotated_feature_align_block.mlu
- kernels/voxelization/voxelization_kernel.mlu
fix racecheck error.
kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
kernels/generate_proposals_v2/generate_proposals_v2_union1_500.mlu
kernels/rotated_feature_align/rotated_feature_align_block.mlu
kernels/voxelization/voxelization_kernel.mlu
> [Fix](mlu-ops):fix racecheck error.

- docs/design_docs/logspace/logspace.md
- kernels/logspace/logspace.cpp
- kernels/logspace/logspace_block.mlu
Thanks for your contribution and we appreciate it a lot. 🚀🚀
1. Motivation
fix gen_case bug.
fix nan/inf bug
modify design docs
2. Modification
docs/design_docs/logspace/logspace.md
kernels/logspace/logspace.cpp
kernels/logspace/logspace_block.mlu
> [Fix](mluOpLogspace): Fix logspace bug.

- core/gen_case.h
fix gen-case dump float16 bug.
core/gen_case.h
> [Fix](mlu-ops): fix gen-case dump float16 bug.

- docs/MLU-OPS-Compile-Develop-And-Test.md
add build option '-p/--perf' user guide
docs/MLU-OPS-Compile-Develop-And-Test.md
> [Docs](mlu-ops): add build option '-p/--perf' user guide

- kernels/lgamma/lgamma.cpp
> [Fix](mluOpLgamma): Fix lgamma gencase bug.

- CMakeLists.txt
> [Feature](mlu-ops): compiled by cpp17

- kernels/sparse_conv/indice_convolution_backward_filter/indice_convolution_backward_filter.cpp
> [Fix](mluOpIndiceConvolutionBackwardFilter): fix gen_case function

- build.property
update cntoolkit and cnnl version,
build.property
> [Docs](mlu-ops): Update cntoolkit to 3.15.1, cnnl to 1.27.4

- build.property
Update toolkit 3.15.2
build.property
> [Docs](mlu-ops): Update toolkit 3.15.2

- kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
- kernels/generate_proposals_v2/generate_proposals_v2_union_default.mlu
fix memcheck bug detected by cnsantizer
kernels/generate_proposals_v2/generate_proposals_v2_nms_utils.h
> [Fix](mluOpGenerateProposalsV2): fix memcheck bug.

- docs/api_guide/update.rst
Correct the date in the documentation.
modified:   docs/api_guide/update.rst
> [Docs](mlu-ops): Update version date.

- CMakeLists.txt
- independent_build.sh
> [Feature](mlu-ops): Update Cmakelists.txt for --no-neuware-version-check

- CMakeLists.txt
> [Feature](mlu-ops): Compile mtp_613 by default

- README.md
> [Docs](mlu-ops): update README.

- build.property
- docs/design_docs/roi_align_rotated/roi_align_rotated_forward_vector.md
- docs/design_docs/roiaware_pool3d_forward/roiaware_pool3d_forward.md
- kernels/psroipool/psroipool_block.mlu
- kernels/roi_align_rotated/roi_align_rotated_block.mlu
- kernels/roi_align_rotated/roi_align_rotated_forward_vector.mlu
- kernels/rotated_feature_align/rotated_feature_align_block.mlu
- tools/coverage.sh
Update toolkit to 4.0.0 and remove deprecated API call.
See Files changed for details.
Use CI as test.
> [Feature](mlu-ops): Update toolkit to 4.0.0 and remove deprecated API call.

- scripts/gen_symbol_visibility_map.py
scripts/gen_symbol_visibility_map.py
exclude redundant symbols
- diff1
- diff2
- diff3
- Job types
Test …
> [Fix](mlu-ops): fix mluops symbol match scripts for lite api

- test/mlu_op_gtest/CMakeLists.txt
auto merge extend proto to mlu_op_proto
test/mlu_op_gtest/CMakeLists.txt
- diff1
- diff2
- diff3
- Job types …
> [Fix](mlu-ops): auto-merge extend proto if new proto file is cloned.

- bangc_kernels.h
- scripts/bangc_kernels_path_config/bangc_kernels_path.json
- scripts/bangc_kernels_path_config/bangc_kernels_path_check.py
- tools/commitlint.py
> [Feature](mluAdamW): update adam_w_lite

- scripts/bangc_kernels_path_config/bangc_kernels_path.json
scripts/bangc_kernels_path_config/bangc_kernels_path.json
print：
config['version']  v1.5.0
config['defaultDeps']  [{'cntoolkit': 'v4.0.0', 'driver': 'v6.0.3'}]
config['optionalDeps']  [{'cnnl': 'v1.28.0'}]
> [Feature](mlu-ops): upgrade bangc_kernls_path.json .

- independent_build.sh
> [Feature](mlu-ops): add cnsanitizer for neuware

- test/mlu_op_gtest/pb_gtest/include/dispatch_enumDtype.h
枚举量每次都要if-else判断才能根据类型启动kernel，希望能已简化的形式书写
使用fold expression（折叠表达式），std::variant, std::visit 特性托管分发操作，开发者书写时只用一种写法
本地编译测试通过
> [Feature](mlu-ops): enumType->datatype

- .github/pull_request_template.md
- independent_build.sh
no more compile 370
modified:   .github/pull_request_template.md
modified:   independent_build.sh
> [Feature](mlu-ops): no more compile 370

- kernels/kernel.h
combine nram and wram to perf for split
> [Feature](mlu-ops):combine nram and wram to perf for split

- build.property
Update toolkit 4.1.0
build.property
> [Feature](mlu-ops): Update toolkit 4.1.0

- tools/perf_analyse/analysis_suite/utils/ptpb_helper/proto_helper.py
> [Fix](mlu-ops): fix perf analyse gen proto.

- CMakeLists.txt
> [Feature](mlu-ops): delete cncc 372 compile

- kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
Enable IO optimization for and compute optimization for better performance.
kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
Use CI test for result.
> [Feature](ms_deform_attn_forward): Optimize IO eff for kernels.

- docs/design_docs/fft/bluestein_fft_01.png
- docs/design_docs/fft/fft.md
- kernels/fft/c2c_fft/c2c_fft_host.cpp
- kernels/fft/common/chirpz_aux_block.mlu
- kernels/fft/common/complex_matrix_dot_vector_block.mlu
- kernels/fft/fft.cpp
- kernels/fft/fft.h
- mlu_op.h
- test/mlu_op_gtest/api_gtest/src/gtest/fft/fft_general.cpp
> [Feature](mluOpExecFFT): add bluestein fft for support any size of complex-to-complex fft of float dtype.

- kernels/fft/fft.cpp
> [Fix](mluOpExecFFT): fix pad large length.

- kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
Fix nan/inf input result error.
modified:   kernels/ms_deform_attn/ms_deform_attn_forward/msda_forward_fast_union1.mlu
Use CI as test.
> [Fix](ms_deform_attn_forward): fix nan/inf error.

- kernels/deform_conv/dcn_common/dcn_common.cpp
- test/mlu_op_gtest/pb_gtest/src/internal_kernel/transpose_cpu/transpose_cpu.cpp
- test/mlu_op_gtest/pb_gtest/src/internal_kernel/transpose_cpu/transpose_cpu.h
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.h
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_weight/dcn_backward_weight.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_weight/dcn_backward_weight.h
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_forward/dcn_forward.cpp
- test/mlu_op_gtest/pb_gtest/src/zoo/dcn_forward/dcn_forward.h
modified:   kernels/dcn_forward/dcn_common.h
modified:   test/mlu_op_gtest/pb_gtest/src/internal_kernel/transpose_cpu/transpose_cpu.cpp
modified:   test/mlu_op_gtest/pb_gtest/src/internal_kernel/transpose_cpu/transpose_cpu.h
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_weight/dcn_backward_weight.cpp
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_weight/dcn_backward_weight.h
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.h
modified:   test/mlu_op_gtest/pb_gtest/src/zoo/dcn_backward_data/dcn_backward_data.cpp
modified: …
> [Fix](mlu-ops): modify license of dcn_forward, dcn_backward_weight and dcn_backward_data

- kernels/nms_rotated/nms_utils.h
> [Fix](mluOpNmsRotated): fix macro with brace.

- kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_forward.mlu
Performance optimization 
modified:   kernels/ms_deform_attn/ms_deform_attn_forward/ms_deform_attn_forward.mlu
Use CI test result for test report.
> [Feature](ms_deform_attn_forward): Performance opt for later archs.

- build.property
Update toolkit4.4.0 
modified: build.property
Use CI result as test.
> [Feature](mlu-ops): update toolkit to 4.4.0
